class/Blood Hunter.json

1. Added Order of the Lycan from the separate DM's Guild article
2. Fixed Blood Curses not showing
3. Italicized amplification entries

Blood Hunter

---

subclass/College of the Maestro.json
subclass/TalDorei Campaign Guide.json

More stuff from Matt Mercer: Blood Domain Cleric, Juggernaut Barbarian, Runechild Sorcerer, Cobalt Soul Monk. All from the Critical Role setting book. Also College of the Maestro Bard from DMs Guild.

Tal'Dorei Campaign Guide subclasses

---

creature/Kobold Press; Tome of Beasts.json

Ok, sorry about this, it's a bit of a beast, but you can blame Kobold Press for a lot of that - Tome of Beasts had a truly staggering amount of errata (and they still haven't caught all the bugs - in fact the errata themselves have mistakes, sigh). The other person you can blame is... probably me. I'm guessing that your original data came from the Shaped Script data files perhaps? I made the ToB data file by scraping the PDF but, wow, that was ugly. Not least because Kobold are horrifically inconsistent in both formatting and language. I'm sure I haven't caught all the errors but I think this should fix a big chunk!

fix(data): Formatting and data fixes + errata

---

class/sonaplayer; The Customizable Artificer.json

There were some "stealth" updates (no changelog) in the source document, which have been added.
In addition, a few things were fixed in the conversion:
* subclass features which give an additional benefit at higher levels have an added entry at those levels
* wrong wording of Prodigious Craftwork Improvement
* added links
* formatting

Update & fix customizable artificer

---

item/Faolyn; Encyclopedia Magica.json

Adds the encyclopedia magica released in [this post](https://www.reddit.com/r/dndnext/comments/7vod7v/the_not_really_complete_encyclopedia_magica_now/).
It's missing a bunch of links (spell and item), but that's just too much work for me for too little gain

Add Encyclopedia Magica

---

optionalfeature/Sandwichbear; Notes from the Far Realm.json

Fixes incorrect spell capitalization and adds tags as needed.

Typo and Tag Pass on NftFR Invocations

---

class/KibblesTasty; Artificer (Revised).json
creature/Tobias Beis; Critter Compendium.json

Lots of changes for the Revised Artificer
- Fixed the broken Gadgetsmith subclass, the specializations were showing at the wrong levels and the upgrades weren't formatted correctly
- Fixed the Warsmith's misordering of some upgrades and the Power Fist upgrade had an erroneous prerequisite
- Added a lot of spell, skill, condition, and item links, corrected some incorrect ones
- Updated the source link to the latest GMBinder link from KibblesTasty
- Corrected the starting equipment and proficiencies (added the missing hand crossbow and heavy crossbow)
One small fix for the Critter Compendium, the author was listed as Kobold Press so fixed that to say Tobias Beis

Revised Artificer patch and Critter Compendium author fix

---

class/KibblesTasty; Artificer (Revised).json
creature/Tobias Beis; Critter Compendium.json

Updated Revised Artificer to 1.5.1, the latest version from KibblesTasty
Biggest change was the removal of Runesmith and replacement with Golemsmith and Infusionsmith. The other subclasses had their spells, items, and dice all made linkable.

update: all sublcasses to 1.5.1

---

class/KibblesTasty; Artificer (Revised).json
creature/Tobias Beis; Critter Compendium.json

Moved the upgrades for all Revised Artificer subclasses into Optional Features because they took up way too much space and now you can sort and pick them by level. Added a link for each subclass to their relevant filtered optional features list.

Moved Revised Artificer upgrades to Optional Features

---

subclass/Clan Crafter Hralding; Codex of Allies.json

Updated the "Codex of Allies" entry to include a second subclass. There are many more missing documentation and this PR serves as a test of whether I properly understand the JSON format.

Path of the Bloodrager added to Codex of Allies

---

race/SailorCat; Graftling.json

Removed Bone Appetit trait. Changed Undead to Skeletal to better reflect nature and qualities shared by all skeletal creatures in the bestiary, namely resilience vs. poison. Removed Use an Object from Graftling Physiology. Added the Damage Resistance trait tag.

Update SailorCat; Graftling.json

---

item/AeronDrake; Modular Magic Items.json

They were formatted as {@table Table Name|MMI|display text} and now properly are {@table Table Name|Modular Magic Items|display text}.

Fixing the table links in the items

---

item/TheApoApostolov; Items for Grit and Glory.json

Added "A" properties to ranged weapons to display ranges.
Added "T" properties to thrown weapons to display ranges.
Previously had just used custom properties for these, but it seems the schema requires the in-built properties to be used to display ranges. It would be cool if there was a work around.

Ranges fixed

---

collection/Daniel Nnorth; Slivers and Magical Items.json
collection/Kobold Press; Creature Codex.json
collection/Sean O'Connor; Inkantations.json
creature/Regerem; Book of Beautiful Horrors.json
psionic/Sample - Giddy; Black Lily Techniques.json
schema.json

fix(feats): use correct property names
fix(CCodex (3pp)): fix type on hp 'formula'
feat(schema): add custom psionic types
chore(psionics): use new entity format
fix(ccodex-3pp:new-languages): remove header entry and add {@}
Header entry is partial sentence and not in the text of the Creature Codex.
Add {@check Stealth} link in keeping with style guide.
fix(CCodex (3pp)): add word 'all' in aatxe language section
fix(ccodex (3pp)): fix json structure on kappa alignment
fix(Ccodex (3pp)): fix inset and variant of doomspeaker
fix(ccodex-3pp:war chaplain): correct alignment section
Alignment array elements for 'any lawful alignment' corrected
Issue #282 
-----
modified:   collection/Daniel Nnorth; Slivers and Magical Items.json
modified:   collection/Kobold Press; Creature Codex.json
modified: …

fix(collection): fix errors causing Shape Maker to fail

---

collection/JVC Parry; Call from the Deep.json
collection/Kobold Press; Deep Magic 04 Illumination Magic.json
collection/Kobold Press; Deep Magic 17 Mythos Magic.json
trap/James Introcaso; 20 New Traps.json

Worth taking a look at whatever script you're using to autocheck homebrew. Found a few erroneous conversions of `{@hit #}` to `{@atk #}`, which produces unintelligible and undesired results. File in question is `trap/James Introcaso; 20 New Traps.json`.

Fix typos and minor errors

---

collection/Modnar's Manual of Multiple Métier.json
creature/Modnar; NPCs.json

If all homebrew is loaded, at present the range of CRs to filter on in the bestiary goes from "1 and 125 Xp" to "¼". This was due to issues in homebrew. The first had "1 and 125 Xp" where it should have been "2", and the other had "¼" where it should have been "1/4".

Fix inconsistent CRs for better CR filtering

---

subclass/Middle Finger of Vecna; Abyssal Domain.json
subclass/Middle Finger of Vecna; Destruction Domain.json
subclass/Middle Finger of Vecna; Dread Domain.json
subclass/Middle Finger of Vecna; Dream Domain.json
subclass/Middle Finger of Vecna; Peace Domain.json
subclass/Middle Finger of Vecna; Pestilence Domain.json
subclass/Middle Finger of Vecna; Travel Domain (Redux).json
subclass/SwordMeow; Wind Domain.json
subclass/Valerion; Liberation Domain.json
subclass/Vampirebagel; Dragon Domain.json
subclass/zeek0; Ruin Domain.json

Added to the subclasses folder:
Vampirebagel; Dragon Domain.json 
Valerion; Liberation Domain.json 
SwordMeow; Wind Domain.json |
Middle Finger of Vecna; Travel Domain (Redux).json 
Middle Finger of Vecna; Pestilence Domain.json 
Middle Finger of Vecna; Peace Domain.json 
Middle Finger of Vecna; Dream Domain.json 
Middle Finger of Vecna; Dread Domain.json 
Middle Finger of Vecna; Destruction Domain.json 
Middle Finger of Vecna; Abyssal Domain.json

Added 11 cleric subclasses

---

subclass/Middle Finger of Vecna; Chronomancy Update.json

- Prehistoric Warrior (barbarian subclass), Illiterate Intuition feature: updated description to be dynamic
- Prehistoric Warrior (barbarian subclass), Massive Weapon Fighting feature: added @condition tag to "stunned"
- The Future You (warlock subclass), Grandfather Paradox feature: added @condition tag to "incapacitated"
- Fixed the broken links in the spells for the Chronomancer subclass
- Updated spell descriptions to be more dynamic
- Added spell metadata (spell areas, scaling dice rolls, material costs, conditions inflicted, etc.) 
- Temporal Bubble spell: Fixed typo ("you familiar" to "your familiar")
- Erase spell: Fixed typo ("nonmangical" to "nonmagical")

Dynamic Update: Changelog

---

class/Tyeia; The Mystic Revised.json

Added limitations to make the mystic more specialized
-You can only focus on a certain amount of disciplines at a time, increases with level, like preparing spells
-You can only use effects from disciplines you are focusing on

Update Tyeia; The Mystic Revised.json

---

spell/Jessica Wolfman; The (Not Really) Complete Tome of Spells.json

**Total spells converted:** 227/997
**Progress:** 22.77%
- Shrapnel Shot: Fixes the @scaledice tag in the Higher Levels text
- Sticks to Snakes: Fixed typo - Description, 2nd paragraph - "... which has its own actions" (removed extra "it")
- Stone Spider: Fixed typo - Description, 2nd paragraph - "... which has its own [turn]"
- Lizard Limbs: Linked to the "Lingering Injuries" table, so the information can be shown on hover
- Love's Pain: Description, first paragraph - Changed "If you do" to "On a hit" for clarity
- Death Candle: Fixed typo - added "a candle" to first paragraph

Update - v0.2

---

class/Benjamin Huffman; Pugilist.json

Currently the Pugilist Heart of the City feature does not render correctly in 5e.tools for me: the list of benefits is missing. I've manually imported this modified JSON and it appears to fix the issue.

Fix list definition in Pugilist Heart of the City feature

---

collection/Matthew Mercer; TalDorei Campaign Guide.json

Prefixes "Alternative Resurrection Rule: " to the Taxing Return, Didn't Come Back Right, and The Fading Spirit variant rule titles. This style matches the Downtime Activities, and more clearly and intuitively shows that these rules are more or less mutually exclusive.

Subtle Change: Titles of Resurrection Rules

---

class/Walrock Homebrew; Witch.json

Fixed "dispel mislead" being given as a subclass spell rather than "mislead". Corrected author name in the file name. Updated dateLastModified.

Update and rename Warlock; Witch.json to Walrock Homebrew; Witch.json

---

subclass/Ophiuchus; Path of the Bloodrager.json

The authors didn't finally agree on what to use, so the one thing they wrote gets added /shrug

Add long missing subclass description

---

creature/Isabel Beis; Critter Compendium.json

I saw in the history it was originally Kobold Press. Now this one is also wrong again. lmao
Also added a `convertedBy` array in case someone complains they can't find the converter when they want to file a typo.

Fix author name for Critter Compendium

---

class/KibblesTasty; Psion.json

Incorrect reference name in the Unleashed subclass from a previous version name change

Fixed incorrect reference for KibblesTasty;Psion

---

collection/Sokan; Yastah.json

Fixed custom heavy property for weapons.  Was using the standard 5e.tools one instead of the Yastah one.

Sokan; Yastah Fixed Heavy property

---

subclass/badooga; Fighter Subclasses.json

This just has a few typo fixes.
Also, please don't add this stuff to the inset blocks again. They are supposed to be part of the flavor text, and are not meant to appear in the omnisearch bar as standalone subclass features.

Update badooga; Fighter Subclasses.json

---

class/KibblesTasty; Artificer (Revised).json

Added missing spell list tags to the class table, as well as a few other places.
Tagged stuff in the class starting items/proficiencies block.

(Fixed typos/added tags) for KibblesTasty's Artificer Revised

---

book/Giddy; Sane Magic Item Prices Expanded.json

@TheGiddyLimit 
This is a fairly significant commit that extends the scope of the existing **Sane Magic Item Prices** `book`.
In addition to the book itself containing the tables, the file now also creates a priced item for every item in the list.
Any tags in the `book` itself that previously pointed to the original `item` now point to the priced `_copy`.
Wherever possible `_copy` has been used to create the priced item (_424 items_).
In the case of `Generic Variant`s (_41_) and `itemGroup`s (_10_) the `_copy` syntax didn't seem to work so the data has been duplicated with modifications.
In _4_ specific cases it was also necessary to duplicate the `itemEntry` blocks to get the `_copy`s to work.
A general rule has been applied that the `specific variant` costs are ` [[baseItem.value]] + …

SMIP: Create Priced Item _copies & Redirect Tags to Priced Items

---

subclass/LevelOfExhaustion;Circle of the Sands.json

Original file results in spaces missing in the search query for "Get Homebrew". This resolves the issue.

Replace/update LevelOfExhaustion; Circle of the Sands.json

---

adventure/Kobold Press; Book of Lairs.json

Thease two typos were preventing plutonium from importing adventure.
I am new to thease things. Just vanted to make stuff work in my game so if I did something wrong please  let me know.

Fixed tag typos that were preventing plutonium form importing adventure

---

class/MCDM Production - The Illrigger Class.json

Fixed Moloch's Blessing to show proper ability instead of Fade's description.

Update MCDM Production - The Illrigger Class.json

---

book/Monte Cook; Arcana of the Ancients.json

Fixed typos that broke plutonium import for some creatures and tables. Pointed by @ jaguar on discord.

Fix: AotA typos fix

---

class/KibblesTasty; Artificer (Revised).json

Updated Spells specifically adding a the spellcasting modifier, and the caster type to half caster so that spells generate in charactermancer.
Added upgrades as optional features that get assigned at their appropriate levels

Charactermancer fixes

---

book/Ghostfire Gaming; Grim Hollow Player's Guide.json

Today we learned that item types are case-sensitive. I blame kierann.

Fix breaking typo in GH:PG

---

creature/Dragonix; Monster Manual Expanded.json
creature/Kobold Press; Creature Codex.json

Monster Manual Expanded:
* Remove cantrip block with bad spell tag (statblock in PDF has an empty cantrips label)
Creature Codex:
* Fix spell entries with extra `{@spell` (and fix corresponding braces) in Whisperer in Darkness, Blood Mage (Midgard Version), and Vampire Priestess
* Remove trait from Whisperer in Darkness that appears to be a corruption of two spells

Fix typos in MME and CCodex

---

creature/Dragonix; Monster Manual Expanded III.json
creature/Dragonix; Monster Manual Expanded.json

Small typos + add a `source` and `name` to all the MME3 `altArt`s so they actually work in Plutonium

MME1 and MME3 typos

---

collection/Mage Hand Press; Valda's Spire of Secrets.json

Valda's paladins get their extra spells at the same levels as other oaths. Also fixed in latest PDF.

fix for paladin spell levels

---

creature/teqqqie; Weird Flavor Creatures.json

Fixed some HP values on Deepstar and Giant Deepstar that had been incorrectly calculated, changed the name of the Corpse Flower to Carrion Flower to avoid conflicting with the new official Corpse Flower creature, and also changed creature size to Large, with appropriately modified HP and HD. Removed a feature from Giant Deepstar that it was not intended to have, and appended additional flavor text.

Update teqqqie; Weird Flavor Creatures.json

---

collection/Amellwind; Amellwind's Guide to Monster Hunting.json
collection/Amellwind; Monster Hunter Monster Manual.json

Brings AGMH in line with 6/15 version as updated on Reddit, and some updates to MHMM.
In addition to the last AGMH pull request, this one covers updates to the dungbomb, feats, artificer infusions, and the new jungle statblock, overworld travel rules, and monstie sidekick class. 
The MHMM updates should cover relatively recent changes up until the Fanged Wyverns. More to come later.

AGMH 6/15 Update

---

class/LaserLlama; Alternate Ranger.json

Converted both LaserLlama's Alternate Ranger class, as well as their Alternate Ranger: Expanded document. The .json contains both sources, with all classes, subclasses, and optional features included in the source documents.

BREW-255: Converted LaserLlama's Alternate Ranger

---

class/LaserLlama; Alternate Fighter.json

-Exploits were revamped, from per subclass to subclass agnostic
-Updated books with new/moved sections between Standard and Expanded docs
-Added new subclasses/exploits/fighting styles
-Created optional types for 1st, 2nd, 3rd, 4th, 5th degree exploits
-Added monster stat blocks for new subclass/exploits
-Added feats
-Added links to other classes from the brewer where needed
-Generally updated text and ability descriptions

Updated Alternate Fighter file to v2.5.1

---

spell/Treantmonk; The Treantmonk Variant - Spells.json

This is a conversion of all of Treantmonk's PHB Spell Variants, found on https://treantmonk.wordpress.com/the-treantmonk-variant/. Includes Cantrips and Spells levels 1-9. Also made to be compatible with KibblesTasty's Occultist's Class Spell selection.

Conversion of Treantmonk's PHB spell rebalance

---

class/Aron; Demi-Dragon.json

Adopt the form of a dragon with this race-class combination for the world's greatest roleplaying game
This content includes a class, a race that goes with the class, eight subclasses, aswell as supplemental items, feats, spells, and backgrounds. It is a feature-complete and thoroughly reviewed and playtested option that makes it possible to play a balanced dragon PC—crucially without being a pain to the DM or the other players in the process.

Add the Demi-Dragon 4.5

---

class/johnofbohemia; Witcher Class.json

- `@duce` -> `@dice`
- `@conditioning` -> `@condition`

Fix typos in johnofbohemia; Witcher Class.json

---

book/Ghostfire Gaming; Grim Hollow Campaign Guide.json

"weilding" --> "wielding" in Shadow Steel weapon

Fix typo in Ghostfire Gaming; Grim Hollow Campaign Guide

---

subclass/PosTavern; Artificer Specialist - Caravaneer.json

Missing curly bracket on line 235 causes an error when hovering over or clicking on the Cordon of Arrows spell and the Prayer of Healing spell.

Bugfix: Missing Curly Bracket ( } ) on line 235

---

spell/Frog God Games; Book of Lost Spells.json

I saw the [Abiding Webs](https://5etools-mirror-1.github.io/spells.html#abiding%20webs_bols) spell the other day and noticed the description references the [Web](https://5etools-mirror-1.github.io/spells.html#web_phb) spell, yet it doesn't link to the web spell itself. This change should (theoretically) create a link to the web spell.
I also don't really do the code thing that much, so I just looked at the files and how they did things, and I -think- this is the correct way to do what I want to do. Hopefully I didn't make any mistakes. Thanks!
BeAuMaN#1025 on 5eTools discord.

Adds Web spell link to "Abiding Webs" spell desc

---

class/Aron; Demi-Dragon.json

This patch focuses chiefly on two new subclasses, as well as a handful of additional content in the form of feats, items, and spells. After four years of dedicated work on this content, the Demi-Dragon has been so thoroughly tested and patched that few concerns remain in the class itself; go try it for yourself—it's good fun!
Changes since last version:
Class and Race.
* Demi-Dragons can now choose to be Small
* Rend and Ruin can now trigger on any attack (from any natural weapon attack), and moved Rend and Ruin up to start at level 13 with 1d6
Subclasses.
* Added a new subclass, the Embodiment of the Behemoth, a dedicated tank as concepted by Robert Sparda, with the features Lumbering Behemoth, Natural Overdrive, Hulking Beast, Overpowering Force, Frightful Display, Wounded Defiance, and …

Aron; Demi-Dragon 4.6 Update Patch

---

class/LaserLlama; Alternate Rogue.json

The critical error with Justicar's sources was overlooked in the latest pull.

Actually fixes Alternate Rogue

---

creature/badooga; Minecraft 5e.json

adds Ender Dragon stat block, abbreviates two legendary headers

Update badooga; Minecraft 5e.json

---

class/KibblesTasty; Occultist.json
collection/Amellwind; Amellwind's Guide to Monster Hunting.json
collection/Amellwind; Monster Hunter Monster Manual.json

Adds in remaining monsters from Sunbreak updates, along with changes to gathering and Bow Charge materials as specifically mentioned [here](https://www.reddit.com/r/dndnext/comments/10a0o8s/monster_hunter_monster_manual_and_guide_to/). While this document could still use a slow and thorough re-check - Amellwind's patch notes are never comprehensive, especially in regards to small rewordings - I think this update brings everything important up to speed.
Detailed list of changes:
```
Monsters
Tempered Shogun		
Tempered Daimyo		
Risen Cham			
Gaismagorm			
Risen Kush			
Malzeno				
Risen Toaster		
Blood Orange Bish	
Garangolm			
Lunagaron			
Scorned Magna		
Tempered Astalos	
Espinas				
Tempered Espinas	
Flaming Espi		
Lucent Narga		
Tempered Seregi		
Magma Almu			
Violet Mizu			
Aurora …
```

Update Amellwind; Monster Hunter Monster Manual.json

---

subclass/Elderbrain; Crown of the Oathbreaker Subclass Compendium.json

36 subclasses (3 for each SRD class) from the Elderbrain Crown of the Oathbreaker campaign.

Subclasses from Crown of the Oathbreaker

---

subclass/LaserLlama; Druid Circles.json

Adds seven new Druid subclasses and an alternative Circle of the Land.
EDIT: Nine new subclasses with the addition of Swarm and Tempest. Also adjusted some previous subclasses with this new update.

Add LaserLlama; Druid Circles

---

class/LaserLlama; Alternate Bard.json

* Capstone changed - added choice of 6th/7th level spell to spells known
* Re-ordered feature so they're in order by level
* Re-added feature headers to Conspirator, Mesmer, and Sword Dancer subclasses
* Conspirator Extra Attack changed to Devious Strike
* Re-added inset to Elegant Exploits
* Tweaked various descriptions that were updated from 1.1.0 to 1.1.1

Updated LaserLlama's Alt Bard to 1.1.1

---

subclass/Korvinagor; Circle of Kudzu.json

Change "them" to "it" when referring to a creature, as is standard.

Tweak Circle of Kudzu wording.

---

subclass/Korvinagor; Circle of the Seasons.json

Tweaked text to make it clear that spell/cantrip access was tied to the Seasons Druid's transformation.

Clarified Seasons Druid wording

---

book/Ghostfire Gaming; Grim Hollow Campaign Guide.json

Fix Typo
Also the web editor for a two-character change seems to have destroyed the tab stop size, apologies

Update Ghostfire Gaming; Grim Hollow Campaign Guide.json

---

class/DM_Havuhk; The Witch.json

One Toll the Dead was missing |xge and the other changed 'Soeed' to 'Speed'

two really small typos

---

collection/Jonoman3000; Blazing Dawn Player's Companion.json
creature/Dragonix; Monster Manual Expanded II (v2).json

One flagged by a human, and one by an Excellent™ new [script](https://github.com/Spappz/Tools45eTools/blob/master/tag-checker.ps1) I have written.

Fix @ tags

---

collection/Giuseppe Rotondo; Mysteriously_Missing.json

These tables provide an instant, retroactive story to explain why a character disappeared and was not around during the last session, when a player could not participate in the game.
- Last Seen in Town
- Last Seen in a Dungeon
- Last Seen in the Wilderness

Mysteriously Missing and Merrily Met - Sample

---

subclass/Korvinagor; Circle of Kudzu (v2).json

Removed free casting of Transport via Plants (already able to do so via One with the Weeds).

Circle of Kudzu (v2) feature tweaks.

---

class/D&D Wiki; Swashbuckler.json

"MB" is incorrect, should be "TB" for "Trickster Bomb", the optional feature type defined at the top of the file.
```
"optionalFeatureTypes": {
"MFM": "Masterful Maneuver",
"SM": "Swashbuckling Maneuvers",
"TB": "Trickster Bomb"
},
```

Update D&D Wiki; Swashbuckler.json

---

class/MCDM Productions; The Illrigger Class.json

Closes #1873

---

collection/SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json

Hellsguard Roegadyn's fire bolt wasn't importing properly, this fixes it.

Fix broken race spells in FFXIVxD&D

---

subclass/Korvinagor; Circle of Kudzu (v2).json

Replaced Longstrider with Expeditious Retreat.

Circle of Kudzu (v2) Circle Spells tweak

---

book/Ghostfire Gaming; Grim Hollow Player's Guide.json

The following spells were missing the "sangromancy" subclass:
- Red Rain
- Steal Immortality
- Theft of Vitae

added missing subschools to GH:PG spells

---

collection/Paper Minitures; Jarlaxle's Bag of Everything.json

With the new UA update, the "generic" dependency is no longer needed

Updated Dependencies

---

book/Ghostfire Gaming; Grim Hollow Campaign Guide.json
book/MCDM Productions; Arcadia Issue 3.json
class/Aron; Demi-Dragon.json
class/ChronicleOfHeroes; Weaveknight.json
class/KibblesTasty; Inventor.json
class/KibblesTasty; Psion.json
class/Walrock Homebrew; Witch.json
class/xMartu; Surgebinder.json
collection/Anthony Turco; Korranberg Chronicle Psions Primer.json
collection/DMsGuild; Rashemen.json
collection/Genuine Fantasy Press; The Compendium of Forgotten Secrets - Awakening.json
collection/Gustavo Ramirez; Zorindis Campaign Setting.json
collection/Haven; All Beneath the Yonder Seas and Streams.json
collection/Jeremy Forbing; Elminsters Guide to Magic.json
collection/Kobold Press; Deep Magic 13 Dragon Magic.json
collection/Kobold Press; Tome of Heroes.json
collection/Plus Three Press; Crystalpunk Campaign Guide.json
collection/Rynosaur94; Planeshift Equestria.json
spell/Jessica Wolfman; The (Not Really) Complete Tome of Spells.json

I originally only wanted to fix the incorrect usage of plural in `spell.duration.type` (e.g.: `minutes` instead of `minute`) which lead to the site displaying a double 's' at the end. I then noticed a few other easy fixes and thought it would be better to do them all at once instead of spamming PRs.
The changes are:
- changing instances of `minutes` / `hours` in `spell.duration.type` to `minute` / `hour`
- changing `bonus action` / `bonus ` (trailing space) in `spell.time.unit` to `bonus`
- fixing an instance where the reaction condition was included in `spell.time.unit`, by moving it to `spell.time.condition`
- removing parentheses from one `spell.reaction.condition`

Fixed inconsistencies in the "time" and "duration" fields of multiple spells

---

class/Matthew Mercer; Blood Hunter (2020).json
class/Matthew Mercer; Blood Hunter (2022).json

Removes the "Proficiency Versatility" features from UAClassFeatureVariants in the Blood Hunter 2020 and 2022 classes, to stop the UA from being forcefully enabled when going to the classes page.

Remove UA from Blood Hunter classes

---

book/Ghostfire Gaming; Grim Hollow Campaign Guide.json
collection/SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json

fixes a typo in the adventure storylines
Also tacked on is a simple typo fix in FFXIV5E

Update Ghostfire Gaming; Grim Hollow Campaign Guide

---

item/enders; Oversized Longbow.json

Adds a homebrew for the Oversized Longbow as a `baseitem` supporting declined 5ET-1173

5ET-1173 Oversized Longbow baseitem

---

adventure/JVC Parry; Call from the Deep.json

Three creatures in here use the same tokens as WotC creatures due to their statblocks being variations of them. However, because they're _substantial_ variations, they're not `_copy`. Migrating one of these from `mirror-1` and _two_ of these from `noads`!
If there's a better way to point `tokenUrl` to an internal image please let me know 👍

Update CftD token images

---

class/KieruSnowbell; Apothecary.json

Resolved an incorrect name on Solar Beacon's first Brewer's Bottle Option, and pushed a buff to Vampire's Edge to make Stem the Flow a more appealing ability to use.

Update KieruSnowbell; Apothecary.json

---

magicvariant/aeyana; Gemstones.json

This homebrew is blocked requiring `bonusWeaponAttack` to be made available to `baseitem`s.
`bonusWeapon` is already available as a precedent.

BREW-019; Gemstones

---

feat/ordek09; Pact of the Titan.json

Closes #2027 
A bit strange... this isn't really a feat, it's a multi-level pact, nonetheless it's added.
Fixes:
- Removed `"type": "section"` from root of `feat` object
- Spelling typos

Closes Custom feat #2027

---

book/Ghostfire Gaming; Grim Hollow Player's Guide.json

closes #2025 
fixed errors in conversion of Vermin Lord's Verminkin ability:
> number of swarms summoned is equal to spell slot level, not twice spell slot level
> feature recharges after a short or long rest
> swarms disperse after 1 minute, not 10
> reusing the feature does not end the present use (due to recharge on rest)
Attack reach of Swarm of Vermin also changed to 0 ft. to match book

Vermin Lord Update Ghostfire Gaming; Grim Hollow Player's Guide.json

---

collection/Mage Hand Press; Valda's Spire of Secrets.json

Update Signature Focus to Valda's 1.4
Notable change: Can be used on a simple or martial weapon now, not just simple, and Int applies to both attack and damage rolls.
✅ checked it works by uploading from raw url in my fork

Updated Warmage Signature Focus trick in Valda's Spire of Secrets

---

collection/MCDM Productions; Strongholds and Followers.json

Added missing spells. Fixed empty `{@spell }` object.
I discovered this issue when attempting to search the bestiary with regex. This entry caused the search to fail as parsing broke on the empty spell object.
I also took the liberty of listing out the other spells in the book.

Fix issue with SaF The Queen of Bones.

---

collection/Mage Hand Press; Valda's Spire of Secrets.json

Added "|VSS" to several cantrips so they no longer link to the non-existant PHB version.

Fixed Popout cards not working on some occasions

---

creature/StoneStrix; Monster a Day Compendium.json

Fix typo: Evil Doll type "constuct" -> "construct"

Fix typo: StoneStrix; Monster a Day Compendium.json

---

variantrule/Bovenbrew; Bovenbrew Weapon Arts.json

An alternative take on the BG3 weapon actions system meant to give weapon users more tactical options compared to their option-rich spellcaster party members. 
Also includes some weapon arts meant to work with exotic weapons that I will upload homebrew for later.

Create Bovenbrew; Bovenbrew Weapon Arts

---

subclass/Jagans_eye; Haste Knight.json

Changed status and fixed json reference.

Fixed source json references.

---

spell/Johnny Tek; The Prestige Spells of Illusion.json

Added Orb of Memories, which was previously missing. Also updated a few page numbers to be correct and updated "Silent Speak" to be a Touch spell, as it was implied by the text, but not the range listed in the book.

Added Orb of Memories to The Prestige: Spells of Illusion

---

background/DaveParkinglot; SelerimBackgroundEdits.json
book/MCDM Productions; Arcadia Issue 19.json
class/Dusk Zargoth; Barbarian Rework.json
class/Dusk Zargoth; Fighter Rework.json
class/Dusk Zargoth; Monk Rework.json
class/Dusk Zargoth; Rogue Rework.json
collection/Niels de Jong; Legacy of the Dragon.json
collection/Zordnael; Curse Of Strahd.json
creature/Tychi101; Tychi101's Creatures.json

Suggest using this in the schema `pattern`
`"^https?://(5e\\.tools|5etools-mirror-\\d+\\.github\\.io|raw\\.githubusercontent\\.com\/5etools-mirror-\\d+)/"`

eliminate external-internal refs

---

adventure/Poison Potion Press; Shore of Dreams.json

Updated Storm Mephit to use the Mephits monsterFluff from MM, instead of erroneous description of tempest beast.

Updated Storm Mephit

---

collection/Griffin Macaulay; The Griffon's Saddlebag, Book 2.json
collection/Griffin Macaulay; The Griffon's Saddlebag, Book 3.json

When utilizing the ttrpg-cli software, I ran into issues pulling two images from TGS Book 2 which appear to be related to characters in the image link. I modified the image links to properly match the ones that were set up in the 'gallery' section. 
I also added a change to TGS Book 3 to resolve a missing bonusSavingThrow.

Resolve Occasional Link Error in TGS Book 2

---

collection/Hit Point Press; Humblewood Campaign Setting.json

I noticed the Vulpin is missing "Charm Person" in their innate spellcasting in Foundry. This PR adds it in.
I'd also like to fix the fact that 'Bite' isn't given to the Actor as an action, but I haven't worked out yet how to add it while keeping the `finesse` property.

Add missing spell to Vulpin species

---

class/MCDM Productions; Beastheart.json

The text of `startingEquipment` correctly lists hide armor as the first equipment option on line 1, but the VTT data has chain mail instead. This PR fixes the VTT data.

fix Beastheart starting equipment

---

collection/MonkeyDM; Steinhardt's Guide to the Eldritch Hunt.json

Last time I use the web interface for a commit.
It's all whitespace, just adds 
```json
"colorNight": "bdc7c7",
```

SGttEH - colorNight
