TheGiddyLimit/homebrew

- subclass/Walrock - Paladins.json
Love, Free Commerce and Common Man Oaths.
> Paladins from Walrock Homebrew

- creature/Nord Games; Ultimate Bestiary Revenge of the Hoard.json
Various Fixes. Might need to be re-run through any formatter you're using to update it to new Bestiary format?
> First revisions. All immediately apparent issues resolved.

- feat/silverbass; Adventurer.json
> Update silverbass; Adventurer.json

- creature/Glen Cooper; Monsters of the Guild.json
Fix the fluff so it will actually show up. Remove the duplicated Bog Worm.
> Update Glen Cooper; Monsters of the Guild.json

- creature/Frog God Games; Fifth Edition Foes.json
- creature/Kobold Press; Tome of Beasts.json
- creature/Nord Games; Ultimate Bestiary Revenge of the Hoard.json
- creature/Tobias Beis; Critter Compendium.json
- spell/Frog God Games; Book of Lost Spells.json
Ok, hopefully this is the last of the big data PRs - this one is a bit more manageable.
There are a couple of fixes to ToB which may seem arbitrary - but they help a lot with compatibility with our script and sheet, which actually parse a lot of this stuff to generate more sophisticated behaviours on the VTT... making things slightly more consistent than Kobold Press actually managed with their publication helps a lot to make this work!
> fix(data): Unary minus update +  a few minor fixes for ToB

- item/Faolyn; Encyclopedia Magica.json
> fix(items): fix encyclopedia magica

- class/sonaplayer; The Customizable Artificer.json
* fixed Psychics / Physics mistake
* added subclass spell lists
> fix(class): fix customizable artificer

- subclass/Matthew Mercer; TalDorei Campaign Guide.json
Updated Matthew Mercer's Way of the Cobalt Soul subclass to the latest version.
> Update Way of the Cobalt Soul

- class/Matthew Mercer; Blood Hunter.json
Updated Matt Mercer's Blood Hunter class with the latest changes.
> Update Blood Hunter Class

- class/Middle Finger of Vecna; Witch.json
Added fluff for Middle Finger of Vecna; Witch
> Middle Finger of Vecna; Witch - Added Fluff

- spell/Rynosaur; Archive of Arcane Aggression.json
A supplement geared towards battlemages to boost their usability
a little. The spells are a small collection and addition to a much
bigger Homebrew and have been tested for quite some time.
> Archive of Arcane Aggression

- background/Brewskii; Silver Thorn Background.json
I hope I'm doing this right, please let me know if there's any problems.
> feat(background): add Knight of the Silver Thorn

- subclass/Way of the Dragon.json
Updated the text to reflect the gmbinder link
> Balanced the Way of the Dragon

- subclass/Way of the Dragon.json
Replaced Dragon Wings with Frightful Presence
> Update Way of the Dragon.json

- collection/Haven; All the Lights in the Sky are Stars.json
Fixed a typo and swapped the discord link
> Update Haven; All the Lights in the Sky are Stars.json

- adventure/Limitless Adventures.json
Have added two encounters to Limitless Adventures.
Hopefully this works.
> Limitless Adventures Update

- collection/Skybug12; Mousefolk 2_2.json
Added to the collections folder. Contains two subclasses from the original document located here: https://drive.google.com/file/d/0B6eHVaEIoWbBZWRid0tkMnhPMXM/view
> Added Skybug12's Mousefolk Homebrew

- collection/Shawn Merwin; Deep Magic 13 Dragon Magic.json
- collection/index.json
only added the spell section of the book
> Added Deep Magic 13: Dragon Magic to Collection

- collection/Anthony Turco; Korranberg Chronicle Adventurers Almanac.json
- collection/Scott Carter; Deep Magic 1 Clockwork Magic.json
Deep Magic 01: spells
Korranberg Chronicle Adventure Almanac: feats & spells
>I plan on also adding the subraces for KCAA, but could not find a way to do it without adding the entire race again (Elf and Khorvaire Elf)
> added Deep Magic 1 and Korranberg Chronicle Adventure Almanac

- class/Middle Finger of Vecna; Alchemist.json
- Change 18 to 19 in Ability Score Improvement 
- Quick Build instead of Quck Build
> Level error and other

- book/Unknown; Shelza Ir.JSON
- book/Vincent Betternfeld; Runic Roulette.JSON
and a functional problem with another book.
> Festival 13 of 17

- feat/Godfall; Godfall Feats.json
Fixed feats that had ability score increases listed twice.
> Update Godfall; Godfall Feats.json

- collection/Godfall.json
> Update to Godfall collection to add custom crafting materials and table

- class/Shadowsocks; Companion
https://homebrewery.naturalcrit.com/share/HyrZKEiimV
> Added Companion Class

- feat/silverbass; Adventurer.json
Fixed references to the way Wild Magic used to function. Also upped the damage.
> Adjustment to Elemental Surge

- feat/silverbass; Adventurer.json
Added Eyes of the Rune and Eyes of the Witch
> Removed Invocation Feats

- feat/silverbass; Adventurer.json
> Changes to Eyes of the Witch and Blood Magic

- feat/silverbass; Adventurer.json
> Fixed a Typo

- collection/Arcana Games; Arkadia.json
I have no idea what I am doing, but this seem to send my file your way. With luck this is where I am supposed to post this.
> Arkadia json

- collection/aeyana; Mashiros Manual of Monstrous Magic.json
First Upload, for easier review and editing.
Not released yet; will be updating some hyperlinks after official release.
> Uploading M4

- feat/silverbass; Adventurer.json
> Reworded Smite to work with fists

- creature/Metabot; Handbook of Slime Rheology.json
- Re-sorted creatures to be in the same order as the source PDF.
- Added missing condition immunities to various slimes.
- Updated source to what seems to be the most up to date version.
- Updated the Leap ability of the Pounce slime to match the current PDF version's description.
- Added the table from the last page of the PDF
> Update Metabot; Handbook of Slime Rheology.json

- subclass/Matthew Mercer; TalDorei Campaign Guide.json
Adding everything except pictures and the bookdata of chapter 2, also fixing issues I've found with the subclasses.
I believe that it will need to be moved to Collection from Subclass.
> Update Matthew Mercer; TalDorei Campaign Guide.json

- race/SailorCat ; Graftling.json
I hope I did this correctly. I apologize if not. Adding a new homebrew race.
> Create SailorCat ; Graftling.json

- item/Faolyn; Encyclopedia Magica.json
* Links were not working
* Some search/replace errors were introduced in a update
* Some items were missing
* Some tables had wrong dice/result numbers
> Fix encyclopedia magica

- race/SailorCat; Graftling.json
A couple minor presentation edits and one rule edit.
> Update SailorCat; Graftling.json

- collection/Matthew Mercer; TalDorei Campaign Guide.json
saw that the matt mercer cobalt soul entries hadn't been updated yet so i fixed it
> updated the matt mercer cobalt soul monk entries

- race/SailorCat; Graftling.json
Size and Languages became Grave Inheritance. Bone Appetit and Marrowsense reworked. Pared or reworded description text where possible to favor conciseness. Overall polish.
> Update to 2.1.0, Polish

- collection/aeyana; Mashiros Manual of Monstrous Magic.json
Idk why the dif is so big; i think the spaces got messed up somehow
> Spell Updates and Typo Fixes

- collection/aeyana; Mashiros Manual of Monstrous Magic.json
Also added the Inset and added SGT tags
Diff is probably big due to the tab/space thing
> Update aeyana; Mashiros Manual of Monstrous Magic.json

- subclass/Clan Crafter Hralding; Codex of Allies.json
Made sure to switch indentation to tabs and clean up the fork so that commits work properly again
> Ranger Conclaves

- subclass/Clan Crafter Hralding; Codex of Allies.json
Rogue and sorcerer subclasses added, reckless casting tables for reference in search bar.
> Daggers and Sorcery

- collection/IrishBandit; Rule of Law.json
- table/Orrex; The Net Libram of Random Magical Effects.JSON
Patreon Reward
and
Fixing case type error that prevented ROL showing its source correctly
> Modnar patreon & Error fix

- collection/aeyana; Mashiros Manual of Monstrous Magic.json
Checked that it doesn't error or do anything funky when the class is not loaded.
> Added support for the Hunter class

- class/aeyana; Hunter.json
Had an issue last time; should be good now
> Moved Hunter's Technique to show in class table

- subclass/Zachary G Paiva; The Rule of 12 Subclasses.json
> Create Zachary G Paiva; The Rule of 12 Subclasses.json

- subclass/Clan Crafter Hralding; Codex of Allies.json
All the warlock content is complete and seems to be in working order.
> Warlock Content

- feat/SailorCat; Graftling Feats.json
Adds feats for the graftling race.
> Create SailorCat; Graftling Feats.json

- class/sonaplayer; The Customizable Artificer.json
Simple update with some fixes of the author
> Update class sonaplayer; The Customizable Artificer

- subclass/Clan Crafter Hralding; Codex of Allies.json
Primeval Guardian has been fixed so that its subclass features appear in the correct order.
Wizard subclasses are now complete.
With this, Codex of Allies is completed as well! 😃
From here, I'll only be making changes if there are mistakes that I can correct.
> Wizards of Typos

- class/Benjamin Huffman; Pugilist.json
Added Patreon FIghting Club, retained Sweet Science (now deprecated)
> v3.5 update

- collection/aeyana; Mashiros Manual of Monstrous Magic.json
Moved Alter Self & Enlarge/Reduce's options to Higher Level
> Moved stuff to Higher Level

- collection/Matthew Mercer; TalDorei Campaign Guide.json
> Taldorei Picture links

- class/Casteliad; Shadow Assassin.json
Would you mind adding this to rep. -Thanks
> Homebrew Class

- book/Richard Bastow; The Noble Art of Jousting.json
- class/Middle Finger of Vecna; Tattoo Classes.json
> Add Classes; and fix typo

- item/TheApoApostolov; Items for Grit and Glory.json
Signifies addition of ranged weapons, ammo and the prettying up of the file
> Change File Version

- item/TheApoApostolov; Items for Grit and Glory.json
I done fucked up when copy pasting, just a simple change, I promise this is it, until they choose to update
> fix: great trident name

- item/TheApoApostolov; Items for Grit and Glory.json
Hopefully there isn't any merge conflicts, think Ive got a-hang of this github thing
> fixed author name

- item/TheApoApostolov; Items for Grit and Glory.json
Turns out to show dmg2, the vanilla versatile key has to be used. Whoops, should be fixed.
> fixed versatile

- item/TheApoApostolov; Items for Grit and Glory.json
acSpecial key doesnt put any text for betterR20 5eTools, entries are added to alleviate that. If you can add text of acSpecial for it that would be cool.
> added: entry values for armor for betterR20

- item/TheApoApostolov; Items for Grit and Glory.json
Fixed some meta field/tag/key options.
> Some final updates to the file

- item/hafdon; zorq.json
First pull request for hafdon for zorq homebrew.
Added file with desires format containing metadata
and three items (thunder blanket, figurine of wondrous
power -- onyx wolf, three school mask)
On branch hafdon/master
Changes to be committed:
new file:   item/hafdon; zorq.json
> feat(item): add 3 items to item folder

- collection/Harry Florence; Enchanted Tattoos for 5e.json
- collection/White Wolf; Relics and Rituals.json
Harry Florence; Enchanted Tattoos for 5e.json
- fix: change 'timeing' to 'time'
- fix: change 'effects' to 'affects' where needed
White Wolf; Relics and Rituals.json 
- fix: add syntactic dashes
- fix: delete end paren character
- improve: add @ links for tool references in Tattoist Kit
Changes to be committed:
modified:   collection/Harry Florence; Enchanted Tattoos for 5e.json
modified:   collection/White Wolf; Relics and Rituals.json
> pull request: fix(collection): fix typos and add {@} links

- collection/hafdon; zorq.json
add action:hug and condition:hugged
add item:wyrmblood venom
improve build script to filter on filenames starting with '_'
log collection keys to console
[semver can be found here](https://github.com/hafdon/5etools-homebrew-home/blob/master/docs/semver.md)
> pull request: feat(hafdon/collection): update to v2.1.0

- collection/Dan Dillon; Deep Magic 03 Void Magic.json
Add file, _meta, and 1 feat (Void Channeler)
> Issue #283: Homebrew Deep Magic 03 Void Magic

- feat/aeyana; Adventurer.json
> Update aeyana; Adventurer.json

- collection/Dan Dillon; Deep Magic 03 Void Magic.json
- collection/hafdon; zorq.json
Also minor changes to `hafdon; zorq.json`
collection/hafdon; zorq.json
collection/Dan Dillon; Deep Magic 03 Void Magic.json
>  Issue #283: Add Void Magic spell, feat, spellSchools

- collection/Middle Finger of Vecna; Evil Archetypes.json
- race/darude11; Faceless.json
Added MFOV Evil Archetypes & fixed Faceless race detail
> Evil Archetypes

- collection/Jelke Ludolphij; Tavern of Trinkets.json
The Eye of the Dao, fix to Eye of the Cloven Sage
> Additional Items and Fixes

- spell/Walrock Homebrew; Codex Of Waves.json
Added the JSON for Walrock Homebrew's 'Codex of Waves' spell supplement.
> Walrock Homebrew; Codex of Waves

- book/Middle Finger of Vecna; Wizarding Contests.json
> Fixed typo

- collection/Raul Rosa; The Spiritual Swordsman.json
- collection/index.json
Added a new Homebrew class, the Spiritual Swordsman, along with its Optional Features: The Spiritual Manifestations.
This class was made by my friend and me.
> Added The Spiritual Swordsman class

- class/KibblesTasty; Psion.json
> Updated Psion to 1.2.2

- collection/Flore; Explorer's guide to Xhoria.json
Also realized my "dateAdded" was incorrect, so i changed it to the correct time it was added
> ADD: New subraces to Flore; Explorer's guide to Xhoria

- collection/Kobold Press; Creature Codex.json
Added (I think) all Lair and Regional effects
> Updated missing content from Creature Codex

- collection/aeyana; Mashiros Manual of Monstrous Magic.json
Now works with magic weapons, but ends if disarmed.
> Minor Change on Myrmidon Blade Dance

- collection/Matthew Mercer; Blood Hunter (2020).json
Different "json" and "abbreviation" to BH2020 instead of CR2020
Sources on subclasses
A bit of formatting
> Updated Blood Hunter

- class/Arcane Athenaeum; Swordmage, A True Arcane Half-Caster.json
Added 'Swordmage, A True Arcane Half-Caster' by The Arcane Athenarum
> Added 'Swordmage' by Arcane Athenarum

- class/aeyana; Hunter.json
Added Night Stalker
Fixed some typos
> Version 1.2.6

- collection/Kobold Press; Creature Codex.json
- creature/Frog God Games; Fifth Edition Foes.json
- creature/Kobold Press; Gem Dragons of Faerun.json
- creature/Kobold Press; Tome of Beasts.json
- creature/Regerem; Book of Beautiful Horrors.json
- creature/The_Unapproachable; Veiled Threats.json
- creature/Tobias Beis; Critter Compendium.json
- race/Middle Finger of Vecna; Thri-Kreen.json
- race/Skut; Warforged.json
- subclass/Middle Finger of Vecna; Circle of the Root and Stem.json
- subclass/Middle Finger of Vecna; Ur-Priest.json
- table/Raging Swan; Tables.json
- variantrule/AeronDrake; Simple Guilds.json
- variantrule/Kcon; Group Spellcasting.json
- variantrule/Metabot; Stealth Rules.json
- variantrule/Pwines; Aerial Combat.json
- variantrule/RedCeramicFryPan; Staff Creation Rules.json
I believe that's now all traces of 3pp tags in the repo. Spreadsheet indicates two more sources that have it, but neither seem to be in the repo at all. ¯\_(ツ)_/¯
Also Creature Codex has been marginally improved.
> Anti-3pp Crusade & Creature Codex fixes

- class/aeyana; Hunter.json
> Added Healing Spirit to Spell List

- book/Saidoro; Sane Magic Item Prices.json
- collection/Arcana Games; Arkadia.json
- collection/Haven; All the Lights in the Sky are Stars.json
- collection/Hit Point Press; Humblewood Campaign Setting.json
- collection/IrishBandit; Rule of Law.json
- collection/Jonoman3000; Dark Arts Players Companion.json
- collection/Kobold Press; Deep Magic 01 Clockwork Magic.json
- collection/Kobold Press; Deep Magic 03 Void Magic.json
- collection/Kobold Press; Deep Magic 08 Battle Magic.json
- collection/Kobold Press; Deep Magic 17 Mythos Magic.json
- collection/MCDM Productions; Strongholds and Followers.json
- collection/Mage Hand Press; Mimic Book of Mimics.json
- collection/Matthew Mercer; TalDorei Campaign Guide.json
- collection/Nord Games; Treacherous Traps.json
- collection/aeyana; Mashiros Manual of Monstrous Magic.json
Two new additions (one complete, one half-complete), and some added covers/book data.
> New conversions, book updates

- class/aeyana; Hunter.json
- Ranger's Hunter's Technique: Flurry buffed to 2 attacks at same target.
- Demon Slayer's Regeneration buffed by 1d6, no longer vanishes in sunlight, but rather isn't generated.
- Blood Hunter's Blood Curse buffed with rally mechanic.
> Feature Updates

- creature/BoltNineHomebrew; The King's Army - Complete Monster Pack.json
Added monster pack from BoltNineHomebrew; The King's Army - Complete Monster Pack
> BoltNineHomebrew; The King's Army - Complete Monster Pack

- adventure/Wizards of the Coast; Barber of Silverymoon.json
Added adventure from Dragon+ Issue 12. https://dnd.dragonmag.com/2020/01/15/the-barber-of-silverymoon/content.html
> Add Barber of Silverymoon adventure.

- item/Shamus_Aran; Crazy Jarls Discount Magic Shop.json
Adds Crazy Jarls Discount Magic Shop to the Item folder.
> Add Crazy Jarls Discount Magic Shop

- item/ASunlessSky; Christmas 100 Magic Items.json
- item/ArmedPirate; Hoard of Kryx the Dragon.json
> Adds [Christmas: 100 Magic Items] and [Hoard of Kryx the Dragon]

- item/p4535992; Stonemoon Shop.json
First personal homebrew collection of items from the community
> First personal homebrew collection of items from the community

- creature/p4535992; Humanoid Creature Collection.json
- creature/p4535992; Item (Tool,Furniture,Background) Creature Collection.json
- creature/p4535992; Undead Creature Collection.json
Some bug fix on json.
Update collection with resources from the web community.
Split my collection by type of monsters.
Added links to web resources where possible.
> Bug fix on the json + Update collection from resources of the web

- creature/Igor Moreno; Barovian Vampires.json
Completed Igor Moreno Barovian Vampire Pack.
P.S. Very sorry about the last pull. I saw that I had forgotten to update the json source references and that you corrected them for me. I really thank you.
> Completed Igor Moreno Barovian Vampire Pack

- item/Gemhammer Games; Gemhammer Deck of Plunder - Heartshine Edit.json
Several magic items, potions, scrolls, and miscellany.
> Addition of the Gemhammer Deck of Plunder unique items

- collection/Hit Point Press; Humblewood Campaign Setting.json
- collection/JVC Parry; Call from the Deep.json
I screwed up guessing things. 😔
> Fix font URLs

- collection/Bonus Action; Patreon Free Tier.json
- item/Gemhammer Games; Gemhammer Deck of Plunder - Heartshine Edit.json
[Bonus Action Patreon](https://www.patreon.com/bonusaction/posts?filters[is_public]=true)
> Adding Bonus Action content and further corrections to Gemhammer

- collection/Kobold Press; Creature Codex.json
> Fix broken token URL

- creature/Chris Avellone; Planescape Torment Bestiary.json
A small thing published in Dragon magazine.
> Add Chris Avellone; Planescape Torment Bestiary

- class/KibblesTasty; Warlord.json
- race/Walrock; Awakened Undead.json
Updated KibblesTasty's Warlord for the new 1.4 release and created a new conversion of Walrock's Awakened Undead race, as the existing version was poorly formatted and riddled with errors. 
First time doing a pull request, so hope I didn't botch it.
> Updating KibblesTasty's Warlord and adding Walrock's Awakened Undead

- creature/Vauxs' Discord Homebrew Extravaganza.json
> Update Vauxs' Discord Homebrew Extravaganza.json

- creature/MrVauxs and Kanekuo; Goblin Pack.json
> Update MrVauxs and Kanekuo; Goblin Pack.json

- creature/StoneStrix; Monster a Day Compendium.json
Sylvan Stalker had a broken skill
> Fix broken creature

- collection/Hit Point Press; Humblewood Campaign Setting.json
Also added a colour in the meta and put my name down as a converter. 😎
Apologies for lack of diff, I killed my local repo and couldn't edit in-browser.
> Fix broken backgrounds

- collection/hafdon; zorq.json
> Update hafdon; zorq.json

- collection/Haven; All the Lights in the Sky are Stars.json
> Added limit on Constellation Companion

- class/Troubadore; Versatile Ranger.json
Hello, this is an updated version of my homebrew. An older version was originally submitted to 5eTools by another person.
> Update Troubadore; Versatile Ranger.json

- class/Izzy; Incarnate.json
Only Shape of the Warrior and Celestial Soul converted.
> Added Izzy; Incarnate

- collection/Hit Point Press; Humblewood Campaign Setting.json
Fixed instances of roll -> dice
> Update Hit Point Press; Humblewood Campaign Setting.json

- class/devikyn; Variant Sorcerer.json
Class: Done
Subclasses: 6/6 Done
Optional Features: 12/12 Done
Typos: (Hopefully) Squashed
Tags: Embedded
> Devikyn; Variant Sorcerer

- class/Mkirshnikov; Juggernaut.json
Attempting to update this, will add more in time. Currently only the Extra attacks and Defender subclass are updated, along with some features. Is the extra indenting necessary?
> Update Mkirshnikov; Juggernaut.json

- creature/Kobold Press; Tome of Beasts.json
Fluff for all monsters added.
Added diseases: Darakhul Fever, Arcane Wasting
> ToB: Fluff added

- collection/Kobold Press; Creature Codex.json
fixed typos (thanks to Spappz)
> CCodex: fixed typos

- creature/Alex Clippinger; Ezmerelda's Encyclopedia of Evil.json
Added all monster statblocks and fluff.
To do: 
- images
- rest of book
> Create Alex Clippinger; Ezmerelda's Encyclopedia of Evil.json

- feat/SailorCat; Graftling Feats.json
Added the Grafted Motor Functions feat.
> Update SailorCat; Graftling Feats.json

- class/Zarieth; The Witch.json
Major source update from v1.1 to v3.0
> Update Zarieth; The Witch.json

- book/Walrock Homebrew; Traders and Merchants.json
> Update Walrock Homebrew; Traders and Merchants.json

- race/Walrock; Awakened Undead.json
Fixed typo preventing a feat from loading properly
> Update Walrock; Awakened Undead.json

- class/NEThingMagic; Card Slinger.json
Class is now functional and added 2nd subclass Hand of the Spellcard
> Update NEThingMagic; Card Slinger.json

- creature/Alex Clippinger; Ezmerelda's Encyclopedia of Evil.json
> Update Alex Clippinger; Ezmerelda's Encyclopedia of Evil.json

- subclass/William Hudson King; The Ashen Wolf.json
Added the Ashen Wolf subclass and its Eldritch Invocations from the Compendium of Forgotten Secrets. Gonna be adding spells and other subclasses in the future.
> Create William Hudson King; The Ashen Wolf.json

- subclass/marshmallow_fig; College of Lofi Beats to Study Relax To.json
This is as serious as Big Tiddy Goth GF Warlock Patron, straight out of /r/UnearthedArcana.
> Add marshmallow_fig; College of Lofi Beats to Study/Relax To

- collection/SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json
> Add missing comma from previous update to FFXIV5E

- spell/Trevor Armstrong; Grimlore's Grimoire.json
Many thanks to @ Sirius for the changelist.
> Update Grimlore's Grimoire to last version

- collection/Arcana Games; Arkadia.json
> Update Arcana Games; Arkadia.json

- collection/Tercept; knerd.json
Added the Dragoon Subclass for the Fighter.
> Added Dragoon Subclass (Fighter)

- collection/Tercept; knerd.json
Includes Alchemy items, ammunition options, GV Armors, Variant Armors, Optional Variant Weapon Property Rules, and diseases
> Updates to include items, diseases, optional rules

- class/pippochiri; The Edgelord.json
If there is a typo it's not a bug, it's probably a feature. From /r/UnearthedArcana.
> Add pippochiri; The Edgelord

- adventure/Adventurers League; DDEX1-01 - Defiance in Phlan.json
- adventure/Adventurers League; DDEX1-02 - Secrets of Sokol Keep.json
- adventure/Adventurers League; DDEX1-03 - Shadows Over the Moonsea.json
- adventure/Adventurers League; DDEX1-04 - Dues for the Dead.json
Sorry for the quick followup, I typoed the repo image path. beginner error.
> Fix typoed DDEX coverUrl links

- class/LLComplete; Alchemist Redux.json
- collection/SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json
LLComplete; Alchemy Redux: added tags, fixed broken references, minor cleanup
FFXIV5E: fix broken item reference
> Fix some brews

- collection/Griffin Macaulay;The Griffon's Saddlebag, Book 1.json
> Update Griffin Macaulay;The Griffon's Saddlebag, Book 1.json

- class/Benjamin Huffman; Pugilist.json
Added 5 subclasses from Patreon: Whiskey Fist, Dragonheart,
King of Beasts, Mailed Fist, and Street Saint
> Update Benjamin Huffman; Pugilist.json

- class/laserllama; The Savant.json
Recently, LaserLlama released the final iteration of [The Savant homebrew class](https://www.gmbinder.com/share/-M0ZVK6ndhFyImQPF_aJ). This PR updates the class with the following:
- Adds 'Seeker' subclass.
- Adds and removes features based on 3.0.0 final update.
- Updates entries for updated documentation.
- Adds 'whip' to proficient weapons.
> Savant 3.0.0 update

- subclass/Ken_Silverwood; Eldritch Champion.json
A Warlock subclass by /u/Ken_Silverwood, from /r/UnearthedArcana
> Add Ken_Silverwood; Eldritch Champion

- subclass/Rain-Junkie; Ancient Magic Sorcerer.json
A Sorcerer subclass by /u/Rain-Junkie, seen on /r/UnearthedArcana
> Add Rain-Junkie; Anicent Magic Sorcerer

- subclass/Matthew Mercer; Way of the Cobalt Soul.json
Updated according to the DDB release.
> Update Matthew Mercer; Way of the Cobalt Soul

- subclass/NotTheSmooze; The Falconer.json
A Fighter subclass utilizing falcons to aid you in battle,
> Add NotTheSmooze; The Falconer

- spell/The__In_Complete_Tome_of_Spells.json
I and a couple of friends converted this spellbook. Thought it would be a good addition
> It's a spell book

- feat/KibblesTasty; Feats for Faiths.json
A few feats for faithful characters in the FR setting, by KibblesTasty
> Add KibblesTasty; Feats for Faiths

- creature/themanclaw; Drow Expansion Pack.json
- item/p4535992; Stonemoon Shop.json
- Add Drow Mech from u/serpentine19 (https://www.reddit.com/r/dndnext/comments/45e8wx/homebrew_drow_mech_monster/ )
- Add Ice Items from u/flashpointbrews (https://www.reddit.com/r/UnearthedArcana/comments/gx4lkf/ice_items_four_coldthemed_magic_items_to_keep/)
> Update some of my work

- subclass/LaserLlama; Monastic Traditions.json
3 Monk subclasses in one package.
> Add LaserLlama; Monastic Traditions

- collection/Jonoman3000; Blazing Dawn Player's Companion.json
- collection/Jonoman3000; Dark Arts Players Companion.json
I swear I will never use GitHub Desktop ever again.
> Fix major mix-up between BDPC and DAPC

- item/p4535992; Stonemoon Shop.json
BUG FIX - made some stupid error on my items collection (ty to Tsulex for point this out)
> BUG FIX - made some stupid error on my items collection

- spell/Faolyn; The (In)Complete Tome of Spells.json
Added author's erratas, and added 2 summoned creatures stat blocks.
> Updated Incomplete Book of Spells

- adventure/D&D Duet; First Blush.json
since the creatures are duplicated in the monster and appendix,
I removed the ones in appendix B and referenced them there.
Another minor change is adding the page property to the section entries.
> Remove duplicated creatures

- class/Xesu; The Samurai.json
Did a small rework and rewrite of some features after some time of playtest.
> Update Xesu; The Samurai.json

- table/MVTTCE.json
A list with 18 Variable Traits for Custom Lineage from Tasha's Cauldron of Everything's Custom Lineage Race
> More Variable Traits for Custom Lineage

- collection/Kobold Press; Creature Codex.json
- creature/Kobold Press; Tome of Beasts 2.json
- creature/Kobold Press; Tome of Beasts.json
Last bit was quicker than expected.
Largest file in the repo!
> Complete ToB2

- collection/Andrew Cawood; Monsters of the Underworld.json
May as well make some headway on this
> Create Andrew Cawood; Monsters of the Underworld.json

- collection/Genuine Fantasy Press; The Compendium of Forgotten Secrets - Awakening.json
- Update text and page numbers to v1.6 (text on [The Trove](https://thetrove.is/Books/Dungeons%20%26%20Dragons%20%5Bmulti%5D/5th%20Edition%20%285e%29/3rd%20Party/Genuine%20Fantasy%20Press/The%20Compendium%20of%20Forgotten%20Secrets%20-%20Awakening%20v1.6.pdf))
- Add Keeper of the Depths warlock subclass
> Update Compendium of Forgotten Secrets: Awakening

- feat/winterwulf; O Dragao Verde (Português).json
first issue of my homebrew feats inspired from D&D 3.5. Portuguese.
> first commit

- collection/Niels de Jong; Children of the Dragon.json
The 67 pages of pure scalykind madness is finally converted 😁
> Add Niels de Jong; Children of the Dragon

- collection/Yorviing; Yorviing's Arcane Grimoire.json
My conversion of Yorviing's Arcane Grimoire to 5eTools.
> Initial commit of Yorviing's Arcane Grimoire

- collection/Kobold Press; Creature Codex.json
fixed spell name typo in statblock
> Spell name correction (CCodex)

- collection/Fey Run Labs; The Gunpowder Codex.json
Conversion of Fey Rune Labs "The Gunpowder Codex" to 5eTools.
> Initial commit of The Gunpowder Codex

- spell/Murphen44; WandsNWizards.json
> Update Murphen44; WandsNWizards.json

- collection/Kobold Press; Creature Codex.json
- creature/Kobold Press; Tome of Beasts.json
> Fix Creature Codex

- collection/Clan Crafter Hralding; The Martial Arms Training Manual.json
Swapping the cluttered prerequisite to a table.
> Update Clan Crafter Hralding; The Martial Arms Training Manual.json

- creature/BoltNineHomebrew; The King's Army - Complete Monster Pack.json
- creature/D&D 4ed; Dark Sun Creature Catalog.json
- creature/Igor Moreno; Barovian Vampires.json
- creature/Michael J Winegar; Wanted Scores.json
- creature/themanclaw; Drow Expansion Pack.json
- race/Clockwork Dragon; Races.json
- race/Zagorath; Vryloka.json
- race/p4535992; Homebrew Races.json
> Bug fix for my works

- creature/BoltNineHomebrew; The King's Army - Complete Monster Pack.json
- creature/D&D 4ed; Dark Sun Creature Catalog.json
- creature/Michael J Winegar; Wanted Scores.json
- creature/p4535992; Humanoid Creature Collection.json
- creature/p4535992; Item (Tool,Furniture,Background) Creature Collection.json
- creature/p4535992; Undead Creature Collection.json
- creature/themanclaw; Drow Expansion Pack.json
- Added BoltNineHomebrew; Monsters of the Apocalypse
- Bug fix image on Darksun Creature Catalog
- Upgrade reference json and abbrevation from my old work
> Added BoltNineHomebrew; Monsters of the Apocalypse

- creature/Kobold Press; Tome of Beasts 2.json
> Update Kobold Press; Tome of Beasts 2.json

- creature/Dragonix; Monster Manual Expanded II.json
I forgot to change the URLs for all the images after testing 😔
> Fixes to previous Monster Manual Expanded II addition

- collection/Niels de Jong; Children of the Dragon.json
- collection/SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json
- Updated Children of the Dragon to fix an error that cause brew purge.
- Updated FFXIV5E to match the most recent source.
> Update two brews

- collection/Keith Baker; Morgrave Miscellany.json
changed "Martial" weapon category to lowercase
> edit: fix typos

- collection/Normiespy96; Master Strikes.json
> Create Normiespy96; Master Strikes.json

- collection/SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json
- collection/heavyarms; the complete armorer's handbook.json
Also fix broken links in FFXIV5E
> Add heavyarms; The Complete Armorer's Handbook

- feat/ImFromNASA; Talent Trees (Modified).json
Psionic rewording and wild talent.
> Update ImFromNASA; Talent Trees (Modified).json

- adventure/Wizards of the Coast; X Marks the Spot.json
> Update Wizards of the Coast; X Marks the Spot.json

- recipe/Sample - Giddy; Toast Sandwich.json
Update Recipe Sample to include allergen groups
> Update Sample - Giddy; Toast Sandwich.json

- recipe/Jef Aldreich; Dungeonmeister.json
Allergen Update
Misc \u2013 use
Added a single {@ dice} tag
> Allergen Update

- spell/Jacob S Kellogg; The Elemental Spellbook: 80 Spells of Ice, Fire, and Lightning.json
Encoded Jacob S Kellogg's Elemental Spellbook :)
> The Elemental Spellbook: 80 Spells of Ice, Fire, and Lightning

- recipe/Sample - Giddy; Toast Sandwich.json
This was my bad in the change I made that added all the allergens.
> Change Peanuts to Peanut to align with all other files

- class/Ranniery Jesuino; The Magus.json
New homebrew class: The Magus v3.2!
> Create homebrew class Ranniery Jesuino; The Magus.json

- subclass/uRavenBranwen; Oath of the Runeblade.json
My first pull request, hopefully this was done correctly.
Changes:
Added Oath of the Runeblade Paladin Subclass
> /u/RavenBranwen; Oath of the Runeblade

- class/SwordMeow; The Atavist.json
- collection/Jonoman3000; Dark Arts Players Companion.json
The Atavist by SwordMeow had incomplete data, now the whole brew is converted.
Also fixed a typo in Dark Arts Player's Compendium
> The Atavist update

- class/lighthazard; Trainer.json
Updated Trainer Class to latest version, using feedback from Reddit and other sources.
> Crazyfuton patch 1

- collection/Sokan; Yastah.json
Adding 1st batch of feats to yastah
> Yastah Feats Part 1

- collection/Sokan; Yastah.json
> Update Sokan; Yastah.json

- class/SwordMeow; The Atavist.json
- collection/Jonoman3000; Dark Arts Players Companion.json
Added page numbers for the `"book"` content
> Update Jonoman3000; Dark Arts Players Companion.json

- collection/Daniel Whyte;Hidal's Tome of the Esoteric.json
Adding Hidal's Tome of the Esoteric - json is valid per JSONlint.
> Create Daniel Whyte;Hidal's Tome of the Esoteric.json

- creature/Dragonix; Monster Manual Expanded.json
Missing some variant rule text
> Update Dragonix; Monster Manual Expanded.json

- class/KibblesTasty; Psion.json
Updated from 1.2.3 to 1.3 and then from 1.3 to 1.4.1.
Changes made were those included in the respective change logs by the original author.
> Update KibblesTasty; Psion to version 1.4.1

- class/KibblesTasty; Warlord.json
Updating Kibblestasty's Warlord from version 1.4 to to version 1.4.1.
> Update KibblesTasty; Warlord.json

- book/MCDM; Arcadia Issue 2.json
Uploaded Arcadia Issue 2 conversion
> Arcadia Issue 2 conversion upload

- collection/Creature Club; Creature Club Homebrew Collection.json
> Update Creature Club; Creature Club Homebrew Collection.json

- collection/SailorCat; GachaBox.json
Adds d1000 table, base item, items, item variants, and item groups.
> Create SailorCat; GachaBox.json

- collection/Benevolent Evil; The Elements and Beyond.json
TEB had Tiny races that broke the Races page and some subraces was missing fluff/additional spells
> Fix broken TEB

- creature/Dragonix; Monster Manual Expanded II.json
- creature/Dragonix; Monster Manual Expanded.json
A new version came out. Fixed the things mentioned in the changelog but I am very doubtful that previous erratas were actioned upon. That said, the brew isn't even that good imo so I don't care 😎
> Update: Dragonix; Monster Manual Expanded [2]

- collection/Sesserdrix; Spelljammer - More Adventures in Space.json
> Add initial Spelljammer - More Adventures in Space support

- class/Mkirshnikov; Juggernaut.json
> Update Mkirshnikov; Juggernaut

- collection/Daniel Whyte; Hidal's Tome of the Esoteric.json
Updated Conqueror subclass of the Warlord to amend link issue
> Update Daniel Whyte; Hidal's Tome of the Esoteric.json

- collection/Heavyarms; The Complete Armorer's Handbook.json
- collection/SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json
Title. Minor typos and one breaking feature was fixed.
> Fix typos in TCAH and FFXIV5E

- subclass/Ken_Silverwood; Eldritch Champion.json
Updated the brew to the latest version.
> Update Ken_Silverwood; Eldritch Champion.json

- subclass/Matthew Mercer; Oath of the Open Sea.json
- Nestled Tenets correctly
- Spelled "Tenets" correctly
> edit: fix formatting/typos

- collection/Anthony Turco; Korranberg Chronicle Adventurers Almanac.json
See https://github.com/TheGiddyLimit/homebrew/issues/893
Old version just had the class, feats, items, and a few other things. Update has everything else and is updated to the newer version.
> Major update to Adventurer's Almanac

- book/Monte Cook; Arcana of the Ancients.json
general fixes on itens (mostly relics) and added the foundryType as well
> addition of foundryType to itens and fixes

- class/Foxfire94; Astartes Inititate.json
- spell/Foxfire94; Advanced Arcaneries.json
Right, hopefully this is what you meant for me to do when you said to close the other PR, delete my old fork, create a new one, add the files I changed in the old PR to the new fork then submit a new PR. I probably seem like an idiot though.
> Updates to files

- race/BatsDiverseEquestrianRaces.json
Diverse Equestrian Races v4 is ready to be uploaded!
> Diverse Equestrian Races

- collection/Anthony Turco; Korranberg Chronicle Psions Primer.json
From v1.03 to 1.05:
Added new class: Icon
Spellchecking and updated language structure
New NPC and creature statblocks
New race
> Update Anthony Turco; Korranberg Chronicle Psions Primer.json

- class/MCDM Production - The Illrigger Class.json
JSON for the Illrigger class, sub-classes, spells, and NPCs. BREW-95
> MCDM - The Illrigger

- book/Zachary Truscott, Nelson DeMeester; Grom's Guide to Potion Brewing.json
File uploaded for Sir Robin(Danger Mouse)#4928
> Add  Zachary Truscott, Nelson DeMeester; Grom's Guide to Potion Brewin

- class/KibblesTasty; Occultist.json
- subclass/Cephei_Delta; School of Geometry.json
This pr includes an update to the KT Occultist to bring it up to v1.1 as requested in Discord, as well as a newly uploaded conversion for an unrelated wizard subclass.
> Update "KibblesTasty; Occultist"; Add "Cephei_Delta; School of Geometry"

- collection/Mogrit; The Technomancer's Textbook.json
Update to the file following the book's update
> Update Mogrit; The Technomancer's Textbook.json

- creature/p4535992; Community Undead Creature Collection.json
- race/D&D 4ed; Dark Sun Races.json
- spell/Heroes from the Dark Realm; Wizard School of Nethermancy.json
Bug fix spell/Heroes from the Dark Realm; Wizard School of Nethermancy.json and add a new monster on undead community collection
> Bug fix spell/Heroes from the Dark Realm; Wizard School of Nethermancy

- Bogdan Max; Bogo's Homebrews
I think this is what should be done if I want my homebrew to be uploaded to the 5e.tool site. I see that the ones already in the repo are categorized by what they have most in them so if this is useful mine has mostly items.
> Bogdan Max; Bogo's Homebrews

- collection/Amellwind; Amellwind's Guide to Monster Hunting.json
Applies 5/21 update to AGMH, mostly just small tweaks to hunter weapons. Minor editorializing on weapon tables to clarify the new loading property
> Update Amellwind; Amellwind's Guide to Monster Hunting.json

- adventure/Adventures Await; Shipwreck of the Sea Mephit.json
- adventure/Adventures Await; Wrath of the Demon Lord.json
- Uploaded Shipwreck of the Sea conversion by Adventures Await
- Uploaded Wrath of the Demon Lord conversion by Adventures Await
> Added two Adventure Awaits adventures

- creature/Setanna; Creatures.json
- item/Setanna; Magic Items.json
> Setanna; Magic Items 0.2.0

- creature/BoltNineHomebrew; Monsters of the Apocalypse.json
- creature/BoltNineHomebrew; The King's Army - Complete Monster Pack.json
- creature/D&D 4ed; Dark Sun Creature Catalog.json
- creature/Igor Moreno; Barovian Vampires.json
- creature/Michael J Winegar; Wanted Scores.json
- creature/p4535992; Community Elemental Creature Collection.json
- creature/p4535992; Community Fey,Faeries Creature Collection.json
- creature/p4535992; Community Fiend Creature Collection.json
- creature/p4535992; Community Humanoid Creature Collection.json
- creature/p4535992; Community Humanoid Special Creature Collection.json
- creature/p4535992; Community Item (Tool,Furniture,Background) Creature Collection.json
- creature/p4535992; Community Monstrosity Creature Collection.json
- creature/p4535992; Community Undead Creature Collection.json
- creature/p4535992; Community Villains Lore (Deities, Monster) Legendary Creature Collection.json
- creature/themanclaw; Drow Expansion Pack.json
- item/p4535992; Community Items Collection.json
> Bug fix some of my work

- book/MCDM; Arcadia Issue 1.json
- spell/KibblesTasty; Kibbles' Generic Spells.json
- Accidentally converted Kibbles' Generic Spells again eventhough it was already on the repo but also added the book portion, so im uploading it anyway.
- Added the other converter to the convertedBy list
- Fixed a loading issue in the Arcadia Issue 1 adventure
> Added  Kibbles' Generic Spells... again

- collection/Heavyarms; The Complete Armorer's Handbook.json
Fixed "ruleType" typo for the variant rules.
> Update Heavyarms; The Complete Armorer's Handbook.json

- class/badooga; Badooga's Psion.json
Balance change + moved to the class folder
> Update Badooga's Psion

- collection/Sesserdrix; Spelljammer - More Adventures in Space.json
> sjmais: custom weapon properties and equipment, fixes, cleanup

- collection/Yesterday; Class Passives & Feat Tiering.json
Picked up on a couple of formatting mistakes. Fixed them.
> New update. Fixed version.

- class/Brad Johns; The Harbinger.json
> Add Brad Johns; The Harbinger

- class/d'Artagnan; The Witch Knight.json
> Add d'Artagnan; The Witch Knight

- class/Team Morsa; Scion.json
> Team Morsa ; The Scion

- collection/Haven;All Beneath the Yonder Seas and Streams.json
Adding ABYSS Compendium to Collections. JSON has been tested and doesn't appear to break anything.
> ABYSS Compendium

- class/Foxfire94; Astartes Inititate.json
- class/Foxfire94; Lycanthrope.json
Sorry for the quick turnaround on PRs, these two had the old format for subclasses which have now been corrected.
> Subclass fixes

- collection/MonkeyDM; Dark Tides of Bilgewater - Rebalanced.json
> Create MonkeyDM; Dark Tides of Bilgewater - Rebalanced.json

- collection/Yesterday; Class Passives & Feat Tiering.json
> Update Yesterday; Class Passives & Feat Tiering.json

- subclass/SethBlackwood; Blood Knight.json
Added the missing subclass feature.
> Update SethBlackwood; Blood Knight.json

- class/devikyn; The Adaptive Ranger.json
Took the chance to fully explore the Foundry specific data possibilities. It's 👌, great job with all that.
> Add Adaptive Ranger class by Entrench

- collection/Andrew Cawood; Monsters of the Underworld.json
- collection/JVC Parry; Call from the Deep.json
- collection/Jetpack7; Gods and Goddesses Redux.json
- collection/MCDM Productions; Strongholds and Followers.json
- creature/Kobold Press; Tome of Beasts 2.json
- creature/Kobold Press; Tome of Beasts.json
Been sitting on these bug fixes/content updates for a while; may as well submit before it's all lost to bit rot.
> Spappz Edits/Additions

- book/MCDM; Arcadia Issue 5.json
Added Arcadia Issue 5 conversion to books.
> Added Arcadia Issue 5 conversion

- class/William Rotor; The Rouge.json
- subclass/titanomachyRPG; Grief Domain.json
- Updated `William Rotor; The Rouge` to include missing subclasses.
- Added `titanomachyRPG; Grief Domain`
> Updates and Additions

- collection/badooga; Badooga's Monster Guidelines.json
Fixes a single capitalization error in a tag name that caused a bug which took like 30 minutes to find the cause of fuck my life
> Update badooga; Badooga's Monster Guidelines.json

- collection/Haven;All Beneath the Yonder Seas and Streams.json
this stops the DM Screen crashing when this homebrew is loaded.
> Haven;All Beneath the Yonder Seas and Streams - update all featureType values to be arrays

- collection/BucketListMod; Personal Homebrew.json
- collection/Keith Baker; Morgrave Miscellany.json
- Fix incorrect information in Morgrave Miscellaney
- Updated personal homebrew file
> Minor Updates

- book/MCDM; Arcadia Issue 4.json
Fixed Arcadia Issue 4 cover by fixing file ending to match file
> Fixed Arcadia 4 Cover

- class/Matthew Mercer; Blood Hunter.json
Update starting equipment (pulled from Blood Hunter (2020))
Hopefully fixes #1019 but I'm unable to test it
> Update Blood Hunter starting equipment

- class/Foxfire94; Lycanthrope.json
- race/Foxfire94; Tanarukk Fiendish Orcs.json
An update for two brews: a new revision of a class and a typo fix for a race.
> Updates to brews

- book/Ghostfire Gaming; Grim Hollow Player's Guide.json
fixed broken item prices and properties.
> Update Ghostfire Gaming; Grim Hollow Player's Guide.json

- subclass/Fiddlestics; College of the Hand.json
- subclass/IDBN; Gun Mage.json
- subclass/TheSoundOfThunder; Soldier of the Seasons.json
- subclass/ihopethiswork; Path of MAGE!.json
- subclass/pm_me_goth_gf_pics; Oath of Love.json
Added the following subclasses:
- College of the Hand by /u/Fiddlestics
- Gun Mage by /u/IDBN
- Path of MAGE! by /u/ihopethiswork
- Oath of Love by /u/pm_me_goth_gf_pics
- Soldier of the Seasons by /u/TheSoundOfThunder
> Add 5 subclasses

- class/Foxfire94; Astartes Inititate.json
- class/Foxfire94; Inquisitor.json
- class/Foxfire94; Lycanthrope.json
- class/Foxfire94; Spellblade.json
- creature/Foxfire94; Honourable Heroes.json
- item/Foxfire94; Armour, Items, and Weapons Galore.json
- race/Foxfire94; Gnoll, Kitsune, Man-Ogre, Rat-men Races.json
- race/Foxfire94; Tanarukk Fiendish Orcs.json
- spell/Foxfire94; Advanced Arcaneries.json
- subclass/Foxfire94; Brick Brawler Monk.json
- subclass/Foxfire94; Brute Fighter.json
- subclass/Foxfire94; Explosion Wizard.json
- subclass/Foxfire94; Primaris Lieutenant.json
Updates for 13 of the brews in the repo, mainly wording fixes and some minor additions to each; apologies for the earlier closed request.
> Update to Foxfire94's brews

- adventure/D&D Duet; Third Times the Charm.json
- adventure/Nerd Herd; Adventure Book - 1.json
- variantrule/Modnars Mission Mandates.json
Finishing the adventure; adding first of Onerios Campaign
> two update

- collection/Haven;All Beneath the Yonder Seas and Streams.json
Monster conversions had HP wrong for almost all entries
Spell, monster, and item references in the items were all wrong
I fixed this shit
Never ask me for anything ever again.
> The Last Patch I'm Doing for This Shit

- book/Dave Eisinger; Discerning Merchant's Price Guide.json
Hopefully I did the _meta tags correctly
> Discerning Merchant's Price Guide homebrew

- variantrule/VaranSL; Brewer's Supplies.json
> Add VaranSL; Brewer's Supplies

- book/Giddy; Sane Magic Item Prices Expanded.json
Also minor typo for X-ray ring which needed to be lowercase.
> Convert `itemGroup`s to `_copy` and add fluff images through `_copy`

- collection/Mage Hand Press; Dark Matter - Partial.json
Updated the various meta fields, and added an extension to the file. Oops!
> Update and rename Dark Matter

- collection/Rsquared; Martial Prowess.json
> Fixed broken filters in Martial Prowess

- class/Rain-Junkie; Dragon Knight.json
minor changes, reformatted JSON for readability
> Update Dragon Knight class to 8.1

- creature/p4535992; Community Construct Creature Collection.json
- creature/p4535992; Community Fey,Faeries Legendary Creature Collection.json
- creature/p4535992; Community Fiend Creature Collection.json
- creature/p4535992; Community Humanoid Creature Collection.json
- creature/p4535992; Community Humanoid Gnoll Creature Collection.json
- creature/p4535992; Community Humanoid Orc,Goblin,Hobgoblin Creature Collection.json
- creature/p4535992; Community Undead Legendary Creature Collection.json
- spell/p4535992; Community Spells Collection.json
Add some creature and update some old work.
Rather than letting them get dust, I add them to the project.
> Add some creature and update some old work

- class/Rain-Junkie; Dragon Knight.json
No JSON formatting changes this time
> Add Garden Practice subclass to Dragon Knight class

- background/D&D Wiki; Featured Quality Backgrounds.json
- feat/D&D Wiki; Valiant.json
- Feat: Valiant
- Background: Adventurer
- Background: Cook
- Background: Cook (Variant)
- Background: Farmer
- Background: Lone Survivor
- Background: Mage Hunter
- Background: Slave
- Background: Unknown
> Add D&D Wiki materials

- collection/Sesserdrix; Wildjammer - More Adventures in Space.json
Some minor text fixes, no functional changes.
> Spelling and copy fixup for Wildjammer

- collection/SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json
Updated `SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json` to the recent October 24th 2021 release.
> Update FFXIV5E to latest release

- collection/JVC Parry; Call from the Deep.json
- collection/Mage Hand Press; Mimic Book of Mimics.json
- collection/Nord Games; Treacherous Traps.json
- creature/Dragonix; Monster Manual Expanded.json
- creature/Kobold Press; Creature Codex.json
- creature/Kobold Press; Tome of Beasts 2.json
- creature/Kobold Press; Tome of Beasts.json
A number of small corrections to various brews I did.
> Fixing typos and etc.

- class/Vladimir Popov; Sorcerer Reworked.json
Includes subclasses, metamagic and base class changes.
> Add Sorcerer Rework

- collection/SilentSoren; 5th Edition D&D x Final Fantasy XIV - Classes and Races Compendium.json
- item/Numbers1999; Sword of 10000 Cuts.json
A weapon for those that truly studied the blade.
Also includes some minor schema fixes for FFXIV5E
> Add Numbers1999; Sword of 10000 Cuts

- spell/Foxfire94; Advanced Arcaneries.json
- subclass/Foxfire94; Oath Daemonicus Paladin.json
- subclass/Foxfire94; Revised Ranger Beast Master.json
Adding a new brew and two fixes for existing brews.
> Fixes for two brews and one new brew

- class/Tandra_Boy; The Empowered.json
Blame them if something breaks 😎
> Add the empowered class on behalf of Lxran

- class/Mage Hand Press;Valda's Spire of Secrets-Warmage.json
Typo; Added "Draw Until" to Deck of Fate feature.
> Update; Mage Hand Press Warmage

- subclass/filmatra; Wizard Community College.json
Closes &BREW-325 Wizard Community College.
First contribution here so feel free to give feedback or point out any mistakes and typos/corrections that could be done.
> Add filmatra; Community College Wizard

- subclass/T. A. Braga; Oath of the Working Class.json
- subclass/Walrock Homebrew; Oath of the Common Man.json
Added the `T. A. Braga; Oath of the Working Class` and `Walrock Homebrew; Oath of the Common Man` subclasses
> Add 2 Paladin Subclasses

- collection/MCDM Productions; Strongholds and Followers.json
- creature/Dragonix; Monster Manual Expanded.json
- creature/Kobold Press; Creature Codex.json
- MME needed `page` keys
- CCodex's Thief Lord creature had a tag error in its AC
- S&F had some schema errors
> Plutonium import fixes for MME + CCodex

- class/Tandra_Boy; The Empowered.json
it's supposed to scale, how did they miss that?
> Edited pure Strength Die from the Empowered Class

- AmbyNavy; The Insatiable.json
After having finally fixed the issues, its done for now. until there are changes to the actual subclass PDF, this is done! Number 1 off the checklist, more to go!
> Submit AmbyNavy; The Insatiable (for real this time)

- class/Foxfire94; Astartes Inititate.json
- class/Foxfire94; Vampire.json
Adding my new "Vampire" class to the repo and some minor adjustments to the Astartes Initiate.
> Adding a new class brew and updating another class brew

- subclass/Spicy Spook; Circle of the Guardian.json
> Add Spicy Spook; Circle of the Guardian: Closes #1184

- book/Ghostfire Gaming; Grim Hollow Campaign Guide.json
- book/Ghostfire Gaming; Grim Hollow Player's Guide.json
Fixed broken image links and missing optional feature types.
> Fix Grim Hollow issues

- subclass/NeonLightDecay; Path of the Nautilus.json
Subclass feature changes and naming updates
> Updated Path of the Nautilus based on feedback and testing

- collection/Griffin Macaulay; The Griffon's Saddlebag, Book 1.json
Candle of Anti-light has been updated on the Reddit post https://old.reddit.com/r/UnearthedArcana/comments/acjhvk/the_griffons_saddlebag_candle_of_antilight/; this also falls in line with other candle items.
> The Griffon's Saddle Bags Book 1 Eratta Candle of Anti-Light

- race/DanDWiki; Elf Orc.json
A rather simple race with complicated implementation. The users will have to import additional features as optional features, until a better implementation can be utilized.
> Add DanDWiki; Elf Orc

- collection/Rsquared; Martial Prowess.json
Version 2.3 and more foundryvtt support.
> Update Rsquared; Martial Prowess.json

- collection/Keith Baker; Morgrave Miscellany.json
Fixed the capitalization in the "classFeature" tag so that the feat would display properly on-site
> fix: incorrect tag

- collection/Agenderarcee'sSorcerousOrigins.json
Finished converting the Agenderarcee Sorcerous Origins and trying to do a pull request. This is the first time I've done it and have no idea how it works otherwise.
> Agenderarcee Sorcerous Origins. 

- collection/Rsquared; Martial Prowess.json
I somehow missed that we could add those now.
> Adding Icons from FoundryVTT to Rsquared's Martial Prowess

- book/Ghostfire Gaming; The Seeker's Guide to Twisted Taverns.json
Added Ch. 2 Rail-Away as that's what I'll be running soon
_**TODO**_
- Add Pictures from book
- Add stat blocks for all listed NPCs
- Add custom made maps (when I work up the motivation to do them)
> Twisted Taverns Partial

- class/itsalittlewaterlizard; The Titan Class.json
> Update itsalittlewaterlizard; The Titan Class.json

- subclass/Lexiette; Wandering Blademaster.json
> Add Wandering Blademaster - Closes #1255

- class/Taron Pounds;  Dancer.json
Initial conversion of Taron Pounds' Dancer class from the DMsGuild, converted by Moko
> Initial upload of Dancer Class

- class/Usocolo123; Votarist.json
Added the Votarist class by Usocolo123 on Discord. Closes BREW-410.
> Add Usocolo123; Votarist Class

- subclass/davedeoreo; Circle of Scales.json
Added a dragon-focused druid class. Closes BREW-411.
> Add /u/davedeoreo; Circle of Scales

- feat/IamMyBrain; Hoard Away From Hoard.json
- feat/SamwiseWrites; Speak of the Devil.json
- subclass/OhWyn; Eldritch Blast Patron.json
Don't have hopes up, they are mainly shitposts. This PR adds the following:
- Speak of the Devil feat by /u/SamwiseWrites
- Hoard Away From Hoard feat by /u/IamMyBrain
- Eldritch Blast Otherworldly Patron by /u/OhWyn
> Assorted homebrew from /r/UA

- feat/aeyana; Adventurer.json
Added the class part of the brew, because someone asked for it.
> Update aeyana; Adventurer

- race/dmblc; The Mimiga Race.json
Adds the Mimiga race by dmblc (me)
> Add the Mimiga race

- class/Foxfire94; Blood Hunter but Balanced.json
> Adding a new brew to the repo

- creature/Sean McGovern; Emirkol's Guide to Devils.json
Contains all the monster statblocks, archdevil statblocks and items. Does not contain any lore nor flavour text.
> Adding new brew: Emirkol's Guide to Devils

- spell/Dev&Girafz; Hyperlanes Gambits.json
This includes all gambits from chapter 7 of HYPERLANES Corebook by Scrivened, LLC
Link to the source: https://www.drivethrurpg.com/product/212154/HYPERLANES-Corebook
> Gambits list from Hyperlanes

- creature/Dragonix; Monster Manual Expanded III.json
Tagging and typos
also nice #1300
> Update Dragonix; Monster Manual Expanded III.json

- class/KibblesTasty; Doggo Sidekick.json
The goodest of bois now accompany you to your adventures! This is an April Fools joke class. Closes BREW-435.
> Add KibblesTasty; Doggo Sidekick

- class/LaserLlama; Alternate Monk.json
Adds the Alternate Monk class. Includes the Alternate Monk Expanded as well.
> Add LaserLlama; Alternate Monk

- class/MCDM Productions; Beastheart.json
Updated name and added missing info to two companions and a class ability.
> Update MCDM Productions; Beastheart.json

- class/LaserLlama; Commoner.json
Adds an (admittedly late) April's Fools joke class, although it is quite charming.
> Add LaserLlama; Commoner

- class/Foxfire94; Blood Hunter but Balanced.json
- subclass/Foxfire94; Oath Daemonicus Paladin.json
Brew updates to the aforementioned.
> Updates to Blood Hunter but Balanced & Oath Daemonicus brews

- variantrule/Matthew Mercer; Corruption Rules.json
- Shifted the major content under the first heading to fix failing `entries`
- Added tags, fixed typos.
- Replaced with \u2013/4 as appropriate
- Fixed `convertedBy`
- Added date of release and colour keys
- Fixed last line of "Cough"
- Added Heroes of Horror link
> Add Corruption rules: closes #1313

- class/KibblesTasty; Occultist.json
- spell/KibblesTasty; Kibbles' Casting Compendium.json
As requested, brings KT Occultist up to v1.2. Also updates KT Generic Spells to 1.2, and KT Casting Compendium to 1.4 aside from psionic spells, as these were related to the Occultist.
> KT Occultist and Casting Compendium

- book/MCDM Productions; Flee, Mortals! preview.json
- creature/MCDM Productions; Flee, Mortals! preview.json
Hopefully with minimal errors!
> Flee, mortals preview

- subclass/Sensitive_Coyote_865; Path of the Masked Scourge.json
A rather crafty Barbarian subclass. Closes BREW-446
> Add Sensitive_Coyote_865; Path of the Masked Scourge

- class/devikyn; Variant Sorcerer.json
> Update devikyn; Variant Sorcerer.json

- collection/Haven; All Beneath the Yonder Seas and Streams.json
Original was accidentally deleted by owner and was accordingly reuploaded, per this reddit comment: https://www.reddit.com/r/UnearthedArcana/comments/nwsvt3/all_beneath_the_yonder_seas_and_streams_abyss/h1avjy5/
> Fixed dead link to Haven's ABYSS pdf

- spell/Sugie; Sugie's Grimoire to the Unknown.json
Sugie's Grimoire of the Unknown
> Add new homebrew repo to spells

- book/Dungeon Rollers; Ancestral Weapons.json
> Ancestral weapons

- class/badooga; Badooga's Psion.json
Removes Temporal Acceleration, Dream Blade is now a bonus action
> Update badooga; Badooga's Psion.json

- collection/Amellwind; Amellwind's Guide to Monster Hunting.json
Adds conversions for newly introduced hunter weapons, Splint Rapier and Wyvern Boomerang
> AGMH new weapons

- creature/teqqqie; Weird Flavor Creatures.json
Clarification and spelling updates to Abyssal Zonathid stat block and description
> Update teqqqie; Weird Flavor Creatures.json

- collection/Benevolent Evil; The Elements and Beyond.json
Duplicated text (see paragraph above deleted)
> fix(json): Typo in Elements and Beyond

- class/Matthew Mercer; Blood Hunter (2022).json
@EldritchTranslator thanks for your work on this.
Changes from your original pull request (#1375):
- Switched json ID to BH2022
- Updated Date of release
- Ran cleaner
> feat(json): Add BH2022, credit to @EldritchTranslator

- collection/Mage Hand Press; Valda's Spire of Secrets.json
Typos, spell tags, duplicated item, filters check, updated subclass spell list so it can be shown on spell and search.
> Update Mage Hand Press; Valda's Spire of Secrets.json

- class/Heavyarms; Gunslinger.json
This is a brew for the Heavyarms Gunslinger, I just finished it and would like it to be added to the repo. Please let me know if I need to make any changes.
> Adding The Gunslinger class

- collection/Jyka; Komalitr.json
Adding two of the three custom classes onto 5etools. Komalitr is like 60% implemented now.
> Haruspex and Kindred classes

- collection/badooga; Martial Power.json
Revises some feats and adds some new ones.
I don't know why the file comparison shows changes to the whitespace when I haven't touched it at all.
> Update badooga; Martial Power.json

- collection/Eva Brown; Hidden Oddities A Witch's Primer.json
Incomplete, but there. Created for personal use and nothing more, so requests on expanding it are gonna go on deaf ears.
> Add Hidden Oddities: Witch's Primer

- background/D&D Wiki; Featured Quality Backgrounds.json
Didn't know how to create the last modified hash, so I deleted it. I presume it auto-generates?
> Add Sleuth background

- class/laserllama; The Savant.json
> Update laserllama; The Savant.json

- class/LaserLlama; The Shaman.json
Converted class, subclasses, optional features, and monster stat block from LaserLlama's Shaman class.
> Converted LaserLlama's Shaman Class

- subclass/BeardedJB; Cosmic Cleric Domain.json
A mild homebrew of the Peace domain for a player.
- Changed Feature names.
- Amended Available subclass spells to fit the theme.
> Cosmic Cleric Domain

- class/LaserLlama; The Shaman.json
Removed duplicate level 10 subclass feature for the Witch Doctor, Selfless Ward.
> Removed duplicate subclass feature

- class/KibblesTasty; Psion.json
- creature/Angry Golem Games; Monster Manual (H-M).json
- creature/D&D 4ed; Dark Sun Creature Catalog.json
- creature/DMDave; NPC Collection Blog.json
- creature/Mistfactor Press; Darklords & Domains.json
- creature/Nicksoliss; The Seven Dragon Overlords.json
- creature/U swtfoley1; Brides & Consorts of Stradh.json
- creature/Web Community; Community Humanoid Legendary Creature Collection.json
- item/Web Community; Shops of Barovia.json
- race/Benjamin Huffman; Saurian Race.json
- race/Zagorath; Vryloka.json
- subclass/Hicks Homebrew; Inner Visage Sorcerous Origin.json
- BREW-334 Saurian, an Original Race for D&D 5e - Benjamin Huffman
- BREW-437 Nicksoliss/Dragon Overlords
- BREW-331 Inner Visage Sorcerous Origin - u/HicksHomebrew
- Added a compendium of Stradh Brides
- Some typo on my works
> Made BREW-334, BREW-437 and BREW-331

- collection/DianaDM; A Series of Stars.json
Corrections from the last update after a more accurate revision.
Hopefully caught all mistakes.
> DianaDM; A Series of Stars.json Corrections

- collection/Plus Three Press; Crystalpunk Campaign Guide.json
optionalFeatureTypes, Evolutionist class, itemType, itemProperty
> Update Plus Three Press; Crystalpunk Campaign Guide.json

- subclass/MonkeyDM; Oath of the Eldritch Hunt.json
> Update MonkeyDM; Oath of the Eldritch Hunt.json

- collection/MCDM Productions; Strongholds and Followers.json
the #1440 is dead long live the #1444
> Update MCDM Productions; Strongholds and Followers.json

- collection/badooga; Elder Evils.json
Fixes a typo in a somewhat important passage. Not sure if/why the whitespace is different when I literally downloaded the file from this repo and edited it
> Update badooga; Elder Evils.json

- spell/Portent Press; Orana's Expanded Spellbook.json
> Started Orana's Expanded Spells

- class/Aussifer; Unchained Warlock.json
BREW-458, Unchained Warlock Class by Aussifer
> Aussifer; Unchained Warlock

- collection/DianaDM; A Series of Stars.json
Fixed Monster fluff, spell scaling, and added UA Ranger subclass compatibility
> Update DianaDM; A Series of Stars.json

- creature/Jade Jawhara; Jade's Crate of Many.json
Hi, sorry this is my first time trying this, I hope I did it all correctly.
> Add Jade's Crate of Many 

- subclass/kacyhasthecandy; Kacy's Castean Classes.json
adds a cleric subclass: Depths Domain
> Add Depths Domain

- class/Bryan Williams; Wychlaran Witch.json
- collection/Garlumpkin; GarlumpkinsMonsters.json
- collection/Kobold Press; Deep Magic Backgrounds, Feats, & Subclasses.json
- collection/Michael LaBossiere; Mike's free Encounters.json
- deity/D&D 3ed; Deities of the World of Claybough.json
- race/Blackbando s Homebrew; Races.json
- race/Heroes from the Dark Realm; Race Collection.json
- spell/Polaron Posadas; Spells of the Unapproachable East.json
- spell/Web Community; Community Spells Collection.json
- subclass/Alice Loverdrive; The Bitch With Many Teeth.json
Add som stuff and the PR from https://github.com/TheGiddyLimit/homebrew/pull/1347, and the PR from  https://github.com/TheGiddyLimit/homebrew/pull/1457 so we can close it for now
> Add some stuff and pr with fix

- class/Matthew Mercer; Blood Hunter (2020).json
- class/Matthew Mercer; Blood Hunter (2022).json
> Update Matthew Mercer; Blood Hunter (2020).json

- subclass/Matthers3; The Moon Dancer Cleric.json
Hey folks! Just made my second subclass, a Bladesinger'ish Cleric based on Drow Lore. Thank you for your work!
> Add The Moon Dancer Cleric Subclass to Homebrews

- class/MisterThr33; Creature Cohorts, the Lich.json
Added The Lich race and class from the Creature Cohorts: The Lich document by u/Mister_Thr33 on GM Binder
> Added Lich Race, Class, and Subclasses

- race/Mr Bat; Bats Diverse Equestrian Races.json
Updating Diverse Equestrian Races to now v5
> Update to DER (v5)

- class/Foxfire94; Lycanthrope.json
> Update to Lycanthrope class brew

- class/KibblesTasty; Occultist.json
- spell/KibblesTasty; Kibbles' Casting Compendium.json
Brings occultist class and kibble's casting compendium up to date. Many typo fixes, some notable rebalances to oracle in particular, and a handful of new spells.
> Occultist 1.3.1; KCC 1.6.2

- subclass/Gelidity; Circle of the Lone Wolf.json
My first attempt to share some of my homebrew. This is a subclass for druid and some accompanying optional features.
> Add Circle of the Lone Wolf

- collection/KibblesTasty; Kibbles' Crafting Guide.json
- race/Yunisverse; Toonkind.json
Some small adjustments:
- Fixed additionalSpells for the base race
- Added toolProficiencies for the base race
- Tagged Grawlix where mentioned and added source to languageProficiencies reference
- Added `{@chance` tag
- Cleaned file, added relevant timestamps etc
- Closes #1565
> feat(json): Add Toonkind closing issue and Progress KTKCG

- class/Ghostfire Gaming; Monster Hunter.json
> Add Ghostfire Gaming; Monster Hunter

- class/LaserLlama; Alternate Ranger.json
Three new subclasses, several abilities changed in accordance to LL's 3.8.1 PDFs on GMBinder.
> LaserLlama's Alternate Ranger 3.7.1 - > 3.8.1

- class/LaserLlama; Alternate Ranger.json
Fixes sync between Hunter's level 15 feature/description, Nomad's level 7 feature/description, level 17 base class feature/description
> Minor feature fixes, no version change

- spell/tactical_hotpants; Artes.json
> Update tactical_hotpants; Artes.json

- class/LaserLlama; Magus Class.json
> Updates LaserLlama's Magus to version 2.2.1

- book/Walrock Homebrew; Fortresses, Temples, & Strongholds.json
> 1.0.1 Fortresses, Temples, & Strongholds update

- class/Blake and Kevin (Blurhy); The Armiger.json
The Armiger Class for 5e, by Blake and Kevin (Blurhy). The armiger is a levitating weapon master class, inspired by swordmages and bladedancers of all kinds. If you ever wanted to be Noctis from FFXV, a Sage from FFXIV, Irelia from League of Legends, Gilgamesh and Archer from the FATE series, or Tenten from Naruto, then this is the class for you.
> The Armiger Class for 5e by Blake and Kevin (Blurhy)

- class/Blake and Kevin (Blurhy); The Armiger.json
Realized the class version on the metadata is incorrect. It's V2.4 and not v2.1. Also fixed one typo and added an @ tag to the Armiger's Armory feature within the Manifested Armory feature just for convenience.
> Update for Blake and Kevin (Blurhy); The Armiger.json

- collection/Junebug; Curse of Strahd Homebrew Items.json
- collection/Junebug; Wayfinders.json
Two files containing my own personal campaign homebrews, each has the unlisted flag set to true. Uploading to repo so they stay up to date when anything changes
> Unlisted personal homebrews

- class/Avaricium; Arbiter.json
Homebrew Class Arbiter adjusted to 5etools json format
> Homebrew Class Arbiter

- class/LaserLlama; Alternate Artificer.json
- class/LaserLlama; Alternate Barbarian.json
- class/LaserLlama; Alternate Fighter.json
- class/LaserLlama; Alternate Ranger.json
- class/LaserLlama; Alternate Rogue.json
There's nothing more to it than the title.
> Little updates, QoL and fixes to Laserllama's classes, adds icons to all exploits

- class/LaserLlama; Alternate Rogue.json
Fixed errors with subclass feature naming
added formatting for die rolls
Fixed some text for skinchanger
> Fixed Errors on Llaserlama's Alt Rogue

- class/LaserLlama; Warlord.json
No longer includes fixes to the Alternate Rogue.
> Updates Laserllama's Warlord

- collection/Amellwind; Amellwind's Guide to Monster Hunting.json
- collection/Amellwind; Monster Hunter Monster Manual.json
This PR includes an update to Amellwind's Guide to Monster Hunting as announced [here](https://www.reddit.com/r/MonsterHunter5E/comments/10a05y7/agtmh_and_mhmm_update_and_possibly_the_last_5e/), featuring: 6 new dragonborn and 3 new races; updates to bow, HBG, and LBG; and a couple of new items. MHMM is in progress, it's a chunky one and I've been a bit behind.
> Amellwind Update 2023-01-12

- _doc/Spec_Copy.md
- collection/Amellwind; Monster Hunter Monster Manual.json
> Update Spec_Copy.md + fix tag

- collection/Nedrapter; Nedrapter's Expanded Dangers.json
> Add Nedrapter; Nedrapter's Extended Dangers

- subclass/Rogue-Umbral Stalker
This adds the Umbral Stalker rogue subclass from crown of the oathbreaker from Elder Brain.
> Umbral Stalker rogue subclass from CotO

- book/2CGaming; Total Party Kill Bestiary - Vol. 1.json
- book/Darrington Press; Tal'Dorei Campaign Setting Reborn.json
- collection/badooga; Elder Evils.json
- creature/Dragonix; Monster Manual Expanded III.json
- creature/Kobold Press; Tome of Beasts 3.json
- creature/Regerem; Book of Beautiful Horrors.json
- creature/The_Unapproachable; Fighting Chance.json
- creature/The_Unapproachable; Veiled Threats.json
My script ignored the niche possibility when nesting `_copy` objects so, now that's fixed, here's some more fluff tags
> More fluff tags

- collection/Nedrapter; Nedrapter's Expanded Dangers.json
- Swap special Orc ability scores to different subraces.
- Swap Champion of the Night options to `refOptionalfeature`s
- fix typos
> Update Nedrapter; Nedrapter's Expanded Dangers.json

- race/DanDWiki; Shadowborn.json
> Added Shadowborn race json

- creature/Tercept; Tercept_s_Terrifying_Thoughts.json
Tercept's creatures used in homebrew campaign inspired by Norse Mythology. All creatures generated on the 5eTools website and then downloaded.
> Added new file to creatures

- class/KibblesTasty; Psion.json
Added Consuming Mind to existing KibblesTasty; Psion.json file, including consumption discipline and consumption talents
> KibblesTasty Psion Class Updated

- collection/Rynosaur94; Planeshift Equestria.json
A full setting guide for the universe of My Little Pony Friendship is Magic.  Trying to blend show accuracy and tone with 5e's general heroic fantasy vibes, I've been maintaining this guide since I created it in 2016.  Contains Races, Feats, Subclasses, Spells, Items mundane and magical, Religions, and more.
> Planeshift: Equestria

- subclass/Korvinagor; Circle of Progress.json
Added an 'urban' druid subclass.
> Add Korvinagor; Circle of Progress

- subclass/Korvinagor; Circle of Progress.json
Just fixing an unrecorded spell that's part of the subclass.
> Added Command spell to subclassSpells section

- class/KibblesTasty; Psion.json
- subclass/Elderbrain; Crown of the Oathbreaker Subclass Compendium.json
Giddy, I hope this is what you meant by making a pull request on the latest version?
> Update Elderbrain; Crown of the Oathbreaker Subclass Compendium.json

- spell/Luriquen; Fiendish_Transformation.json
A gish spell for your Bladesinger or Fiend Pact of The Blade Warlock that let it gain fiendish like abilities, inspired by Draconic Transformation, Tasha's Otherworldly Guise and the Devil Trigger from DmC V.
> Turn into a Fiend with this aweasome spell!

- class/KibblesTasty; Psion.json
fixed one error in consuming mind subclassfeatures
> Update KibblesTasty psion 230221

- subclass/Korvinagor; Circle of Progress.json
Provided better wording for the Progress Druid's Exploited Earth ability.
> Clarified subclass feature

- subclass/GuenMaster; Way of the Stars.json
Updated to match the latest version of source material
> Update GuenMaster; Way of the Stars.json

- subclass/Korvinagor; Circle of the Lamb.json
Added a prey-themed Druid subclass.
> Add Korvinagor; Circle of the Lamb

- table/BlogOfHolding; 5e monster manual on a business card.json
- table/BlogOfHolding; Monster Stats by Challenge Rating.json
This table gives a different way to calculate a Monsters CR that more closely matches the current monsters in published books.
> Provides a different way to calculate Monster CR

- subclass/Korvinagor; Circle of the Lamb.json
Switched out Mirror Image and Freedom of Movement for Invisibility and Dimension Door.
> Adjust Circle of the Lamb circle spells

- subclass/Tsumarru; True Talent Sorcerer.json
Spell check on one of the Subclass feats. I'll be better about it in the future ^^
> Update Tsumarru; True Talent Sorcerer.json

- subclass/Tsumarru; ShadowStalker.json
i forgot to change it from the template i used -__-
> Update Tsumarru; ShadowStalker.json correct mislabeled subclass features

- book/Dungeon Rollers; Ancestral Weapons.json
> Update Dungeon Rollers; Ancestral Weapons.json

- subclass/Tsumarru; Circle of Growth Druid.json
- subclass/Tsumarru; College of Masks Bard.json
- subclass/Tsumarru; Oath of the Elements Paladin.json
- subclass/Tsumarru; Path of the Dragon Barbarian.json
- subclass/Tsumarru; Smooth Criminal Rogue.json
- subclass/Tsumarru; Way of the Ninja.json
An elemental based paladin and a Peter pan inspired rogue
> Add Subclasses 

- race/Foxfire94; Basitin.json
I'm rusty at this; sorry for the mess.
> Adding a new race brew

- subclass/Thewtus; Path of the Cyborg.json
This is for sharing the Path of the Cyborg Barbarian subclass, which I created.
> Path of the Cyborg Barbarian Homebrew

- subclass/Korvinagor; Circles of the Land.json
Added eight caster-focused Druid subclasses as a Land Druid 'rework'.
> Add Korvinagor; Circles of the Land

- subclass/Korvinagor; Circles of the Land.json
Just an additional wording tweak.
> Clarified Frozen Resolve wording further.

- class/LaserLlama; Alternate Bard.json
Includes:
Alt Bard class
3 subclasses
9 spells for the Alt Bard
> Added conversion of LaserLlama's Alternate Bard

- subclass/Korvinagor; Circle of Dreams (Revised).json
Added a tweaked Circle of Dreams with additional features/buffs.
> Add Korvinagor; Circle of Dreams (Revised)

- class/LaserLlama; Alternate Sorcerer.json
Updated from v.2.2.0 to 3.3.0. Additionally, added Alternate Sorcerer Expanded, including new subclasses, spells, and feats.
> Updated LaserLlama's Alternate Sorcerer to v3.3.0

- subclass/Korvinagor; Circles of the Land.json
Extra clarification for how the feature works.
> Tweaked Swamp Circle capstone wording 

- collection/Rynosaur94; Planeshift Equestria.json
- creature/Rynosaur94; Planeshift Equestria Bestiary.json
- spell/Rynosaur94; Divinity Spells.json
- spell/Rynosaur94; Elemental Spells.json
The main file has been updated mostly for more consistency and to correct a few errors. 
Bestiary file added for Equestria themed monsters and NPCs.  
2 smaller files that are some homebrew spells that are commonly used by my group.
> Update to Planeshift Equestria, Added Beastiary File, and then 2 small collections of Homebrew Spells

- class/Benjamin Huffman;The Magus.json
Adding Benjamin Huffman's The Magus class, as well as the relevant magic items, monsters and spells that come with the book. Elements such as the multiclassing prerequisites and the mystic marauder's embalmer's tool proficiency might look a bit whack tho.
> BREW-335 Request completion

- subclass/Korvinagor; Circles of the Land.json
Changed 6th level feature and swapped out Hypnotic Pattern for Water Walk.
> Circle of the Swamp adjustments

- class/Benjamin Huffman;The Magus.json
Fixed an issue with the mystic marauder's statblock
> Magus v1.1

- class/LaserLlama; Alternate Bard.json
* Updated various text and spells
* Added 3 new subclasses
* Added Bardic Fighting Styles for the Sword Dancer subclass
> Updated LaserLlama's Alt Bard to 1.1.0

- subclass/Korvinagor; Circle of the Seasons.json
Added a Druid subclass that switches between 4 spell lists using Wild Shapes.
> Add Korvinagor; Circle of the Seasons

- subclass/Korvinagor; Circle of the Seasons.json
Slight Autumn's Decline nerf, clarified features further.
> Circle of the Seasons wording tweaks

- class/D&D Wiki; Warpriest.json
https://www.youtube.com/watch?v=k_d5jWvBirU
> Create D&D Wiki; Warpriest.json

- subclass/kacyhasthecandy; Kacy's Castean Classes.json
updates my homebrew file with the following changes:
-improved foundry compatibility for existing Depths Domain subclass
-add Scoundrel subclass for rogue
> Update: add Scoundrel subclass

- class/LaserLlama; Alternate Monk.json
Updates Monk and Monk Expanded to 3.0.1
> Update LaserLlama; Alternate Monk.json

- subclass/Korvinagor; Circles of the Land.json
More uses per long rest for Sense the Subconscious.
> Slight Circle of the Underdark Tweaks

- subclass/Korvinagor; Circle of Kudzu.json
Added a Druid subclass with a more versatile Thorn Whip.
> Add Korvinagor; Circle of Kudzu

- class/KibblesTasty; Psion.json
Update KibblesTasty; Psion.json
- Add Wanderer subclass
- Fix minor typos
> Update KibblesTasty; Psion.json

- subclass/Korvinagor; Circle of Kudzu.json
> Kudzu Druid Adjustments

- subclass/Korvinagor; Circles of the Land.json
Made capstone limited to once per long/short rest.
> Circle of the Swamp Tweaks

- adventure/Kobold Press; Tome of Beasts 3 Lairs.json
- collection/MCDM Productions; Strongholds and Followers.json
_of course_ i find a typo literally the moment it gets added to the repo 🤡
> Update Kobold Press; Tome of Beasts 3 Lairs.json

- class/KibblesTasty; Spellblade (Alpha).json
- spell/KibblesTasty; Kibbles' Casting Compendium.json
Updated KCC for v2.1 and Blood Magic Spells (KibblesTasty:BMS). Updated Spellblade spell references to match.
> Update: Kibbles' Casting Compendium spells 2.1

- collection/Mike Mearls; Livestream and Twitter.json
I've added the Whirling Blades Fighting Style that was streamed in 2018, as part of the proposed Ranger fixes. I believe I have done everything correctly. If I can get feedback on this, that would be appreciated.
Kind regards.
> Update - collection/Mike Mearls; Livestream and Twitter.json

- subclass/Korvinagor; Circle of the Seasons.json
Replaced Blindness/Deafness with Vortex Warp.
> Changed Seasons Druid spell list.

- class/ljdankov; BloodMage.json
fixed the name of bloodMage as additional space was issue. Added in a missing optional feature. Fixed formatting structure based on advice from the discord group.
> Update and rename ljdankov; Blood Mage.json to ljdankov; BloodMage.json

- book/Ghostfire Gaming; Stibbles Codex of Companions.json
remove invalid feature type (hello)
> Update Ghostfire Gaming; Stibbles Codex of Companions.json

- creature/Dungeon Dad; Dungeon Dad Statblocks.json
> Update Dungeon Dad; Dungeon Dad Statblocks.json

- creature/Dungeon Dad; Dungeon Dad Statblocks.json
i do not know who i forgot it has that attack.
> Added Klurichir's Battleaxe Attack

- subclass/Korvinagor; Circle of the Rainbow.json
Added a seven-coloured Druid subclass.
> Add Korvinagor; Circle of the Rainbow

- subclass/Korvinagor; Path of Polarity.json
Added a magnetic Barbarian subclass.
> Add Korvinagor; Path of Polarity

- creature/Ben Luke; Skyrim Homebrew.json
This PR closes #1814
Minor corrections:
> Closes #1814

- subclass/Korvinagor; Circle of the Rainbow.json
Changed Dazzling Iridescence slightly.
> Slight Circle of the Rainbow wording tweak.

- creature/Ben Luke; Skyrim Homebrew.json
> feat(#1824): Closes #1824

- subclass/LaserLlama; Paladin Sacred Oaths.json
-Converted 10 subclasses from GMBinder
> Added LaserLlama's Paladin Sacred Oaths

- spell/KibblesTasty; Kibbles' Casting Compendium.json
- Updated compendium to match PDF copy
- Added new spells
- Removed old KGS and KES sources that have now been merged into KCC
- Updated references to Generic Elemental Spells, removed source, updated spell tables
> Updated Kibbles' Casting Compendium to v2.2.1

- collection/LornestFluke; Lornest Fluke's Advanced Undead.json
Multiple fixes as noted in the issue.
Two commits so the diff is available
Closes #1836
> Closes #1836

- subclass/Korvinagor; Circle of Kudzu (v2).json
Added a revamped version of the Circle of Kudzu subclass.
> Add Korvinagor; Circle of Kudzu (v2)

- class/LaserLlama; Magus Class.json
Fixed the Sentinels and Shades subclass, along with some other rearranging of features to be more standard, and some typos
> Update LaserLlama; Magus Class.json

- subclass/Korvinagor; Circle of the Seasons.json
Modified 6th level feature, some spells.
> Additional Circle of the Seasons Tweaks

- subclass/Korvinagor; Circle of Kudzu (v2).json
> Slight feature tweak to Circle of Kudzu (v2)

- class/Troubadore; Runeblade (v0.10).json
- class/Troubadore; Runeblade.json
Deprecated original instead of updating the main file because the previous version was still interesting and the update has redesigned some subclasses entirely
> Runeblade update

- subclass/LeGeneralHugs; Way of the Dragon Warrior.json
- subclass/Loot Tavern Publishing; Spirit Caller.json
adds Dragon Warrior monk by LeGeneralHugs and Spirit Caller sorcerer from Ryoko's Guide to the Yokai Realms (standalone playtest version).
will probably deprecate spirit caller when the full book releases
> add 2 new subclasses

- class/Foxfire94; Blood Hunter Re-Balanced.json
- class/Foxfire94; Lycanthrope.json
- class/Foxfire94; Spellblade.json
- class/TheFlameTouched; Ranger (Revised Spell-less).json
- creature/Foxfire94; Honourable Heroes.json
- item/Foxfire94; Armour, Items, and Weapons Galore.json
- race/Foxfire94; Treefolk.json
- spell/Foxfire94; Advanced Arcaneries 2.json
- spell/Foxfire94; Advanced Arcaneries.json
- subclass/Foxfire94; Blood Magic Sorcerous Origin.json
- subclass/Foxfire94; Revised Ranger Beast Master.json
Updating 8 of my brews, updating the Revised Spell-less Ranger to fix a Foundry import bug and adding two new brews.
> Updates to 9 brews, 2 new additions

- spell/KibblesTasty; Kibbles' Casting Compendium.json
Updated/fixed the following spells:
- Acid Rain
- Brilliant Blade
- Crescent Wind Slash
- Crushing Singularity
- Fling
- Final Flame
> Updated/fixed Kibbles' Casting Compendium

- adventure/Eventyr Games; Kraken's Gamble.json
- adventure/Wyatt Trull; Dungeon of the Mad Mage Companion - Complete Edition.json
- book/HapHazred; Blood in the Company - Players Introduction.json
- book/MCDM Productions; Arcadia Issue 7.json
- book/Will Doyle; Waterdeep City Encounters.json
- class/Taron Pounds; Merchant.json
- class/uI'mFromNASA; Yet Another Ranger Variant.json
- collection/Aeron Drake; Modern Handbook.json
- collection/Ghostfire Gaming; Grim Hollow - The Monster Grimoire.json
- collection/HapHazred; Wyldefarne.json
- collection/Jasmine Yang; Hamund's Harvesting Handbook I.json
- collection/Jasmine Yang; Hamund's Harvesting Handbook III.json
- collection/Jasmine Yang; Hamund's Herbalism Handbook.json
- collection/Jonoman3000; Blazing Dawn Player's Companion.json
- creature/Dragonix; Monster Manual Expanded II (v2).json
- creature/Kobold Press; Warlock Issue 29 - Planar Bestiary.json
- deck/Wyrmwood; Corrupted Tarot.json
- item/M.T. Black; Mordenkainen's Tome of Marvelous Magic.json
- race/D&DWiki; Mogogol.json
- subclass/u_CamunonZ; The Announcer.json
Also chucked some tag fixes in as well to insulate relevant parts of my brews from hypothetical changes in default source handling.
> BREW-683: Mogogol

- class/KieruSnowbell; Apothecary.json
Closes #1918 
Adjustments:
- Fixed mismatched braces in classFeature names
- Renamed `optionalfeatureProgressionlimit` to `optionalfeatureProgression` to make tests pass.
- Ran cleaner/tests
> Closes Kieru Snowbell's Apothecary #1918

- subclass/Korvinagor; Circle of the Rainbow.json
Replaced Divination with Dimension Door.
> Altered spell list of Rainbow Druid

- class/LaserLlama; Alternate Barbarian.json
I'm Dunhier. 
Also adds icons to abilities.
> Update Alternate Barbarian to 2.1.0

- class/DM_Havuhk; The Witch.json
Updated The Witch class to V4 - https://drive.google.com/file/d/1XV7yZ5niDwgwYny8rtSkhxeOdrHfoxVC/view
> Update DM_Havuhk; The Witch.json

- background/D&D Wiki; Drow Breeding Slave.json
just doing my part for #brew-conversion (:
> Create D&D Wiki; Drow Breeding Slave.json

- subclass/AmbyNavy and Moss; The Insatiable.json
- subclass/Blaezix; The Ruffian.json
- subclass/KibblesTasty; Divine Agent.json
Update BREW-577 The Ruffian to v2 for Blaezix.
(Also ran the prettifier on my brews.)
> Update BREW-577 to v2

- collection/Dungeon Dudes; Sebastian Crowe's Guide to Drakkenheim.json
Currently all spells & the Apothecary class has been converted and should be workable within 5etools.
Todo:
- Convert subclasses for all other classes
- Convert all monsters
- Add conditions & effects of Delerium
> Added Sebastian Crowes Guide to Drakkenheim (WIP)

- class/KieruSnowbell; Apothecary.json
Resolving an incorrect name for a feature option.
> Update KieruSnowbell; Apothecary.json

- subclass/Wizards of the Coast; The Revised Ranger Extended Subclasses.json
Adds official subclasses back to the revised ranger UA
> BREW-694: Restore Subclasses to Revised Ranger

- creature/Dragonix; Monster Manual Expanded II (v2).json
> Update Dragonix; Monster Manual Expanded II (v2).json

- subclass/LeBouncer; College of Spectacle.json
- subclass/Mheros, College of Blood.json
- subclass/Mheros; College of Discord.json
Added subclasses for Bard:
College of Spectacle by LeBouncer on Unearthed Arcana Reddit
College of Discord and College of Blood by Mheros on Unearthed Arcana Reddit and GM Binder.
> Added 3 files to homebrew / subclass.

- subclass/somanyrobots; Rimeblade.json
- subclass/somanyrobots; The Agitator.json
- subclass/somanyrobots; The Firestarter.json
- subclass/somanyrobots; Way of Predation.json
Added three subclasses for Rogue:
The Agitator, The Firestarter and Rimeblade by somanyrobots.
Added one subclass for Monk:
Way of Predation by somanyrobots
> Added four subclasses.

- subclass/somanyrobots; The Firestarter.json
Small alteration on the Pyrotechnics abilities for them to display correctly with the BetteR20 script.
> Update somanyrobots; The Firestarter.json

- subclass/Korvinagor; College of Metronomes.json
Added a classical, tempo-manipulating Bard subclass.
> Add Korvinagor; College of Metronomes

- creature/Kobold Press; Tome of Beasts.json
- subclass/Stuart Broz; Wizards of Eberron - Five Arcane Traditions.json
Ran my once-wheneverly [script](https://github.com/Spappz/Tools45eTools/blob/master/tag-checker.ps1) and found two bad tags in one file 👍
> Fix @ tags

- subclass/Korvinagor; Circle of Upheaval.json
Added an earth-shattering Druid subclass.
> Add Korvinagor; Circle of Upheaval

- class/MisterThr33; Creature Cohorts, the Genie.json
Closes #1988 
Changes:
- Ran Proporder and Cleaner
- Migrated subraces to standalone property
> Closes #1988

- spell/Korvinagor; Korvin's Spells and Spell Revisions.json
Streamlined spell's secondary effects into upcast-only.
> Updated Chromatic Orb revision

- collection/Various; Lyra's Legendarium.json
> Add Speak of the Devil Feat

- class/Foxfire94; Blood Hunter Re-Balanced.json
- class/Foxfire94; Inquisitor.json
- class/Foxfire94; Lycanthrope.json
- class/Foxfire94; Spellblade.json
- creature/Foxfire94; Honourable Heroes.json
- item/Foxfire94; Armour, Items, and Weapons Galore.json
- race/Foxfire94; Gnoll, Kitsune, Man-Ogre, Rat-men Races.json
- spell/Foxfire94; Advanced Arcaneries 2.json
- spell/Foxfire94; Advanced Arcaneries.json
- subclass/Foxfire94; Path of the Doomed Slayer Barbarian.json
Various fixes and implementing some changes after schema suggestions were approved.
> Updates to 8 Brews

- collection/Kobold Press; Deep Magic.json
i apparently am only able to notice trivial typos _after_ merging 😐
> Update Kobold Press; Deep Magic.json

- item/Kobold Press; Vault of Magic.json
Forgot to change the status of the file from "wip" to "ready", so i did that and added the date.
> Status change Wip > Ready

- class/LaserLlama; Alternate Warlock.json
> Updates Alternate Warlock to 2.1.0

- class/badooga; Badooga's Warlord.json
- collection/badooga; Libris Mortis.json
Removes references to UA Fighting Styles from two of my brews, which would cause the classes to entirely just not load
> Remove UA Fighting Styles

- charoption/CarbonPioxide; Watchers (Bees).json
Closes #2033
Changes: 
- Added necessary `_meta` section
> Closes #2033

- spell/KibblesTasty; Kibbles' Generic Elemental Spells.json
Didn't add any spells specific to only classes from KibblesTasty's homebrews but I'm pretty sure that was only 1 spell. Anyone else is free to change that ofc.
> Adding Kibbles' Generic Elemental Spells

- subclass/Korvinagor; Circle of Spores (Revised).json
Added a revised version of the Circle of Spores subclass.
> Added Korvinagor; Circle of Spores (Revised).json

- subclass/LaserLlama; Primal Paths.json
> Update LaserLlama; Primal Paths.json

- collection/Mage Hand Press; Valda's Spire of Secrets.json
Added Images to be visualize in 5e Tools
> Added images to "Valda's Spire of Secrets" from Mage Hand Press

- class/Maeglad Olofir; The Samurai.json
Testing out adding my complete class to 5e.tools as official homebrew. Cheers!
> The Samurai

- subclass/Korvinagor; Arcane Ordnance Sorcerous Origin.json
Added a magic missile sorcerer subclass.
> Added Korvinagor; Arcane Ordnance Sorcerous Origin

- spell/Expanded Necromancy Spells by Sonixerse.json
A list of spells created by Sonixerse. From cantrips up to 9th level spells for spellcasters, he added much needed spells to the necromancy school. Have fun
https://www.gmbinder.com/share/-MwCZr0Cd-brD8RhhLBy
> Expanded Necromancy Spell List

- spell/Alex152; Pebble Shower Cantrip.json
Closes #2078
Fixes: 189bf7c
- Removed `siteVersion`
- Removed `basicRules`
- Added `status`
- Removed `scalingLevelDice`
- Swapped `{@dice` tag for `{@damage`
- Split `entries` into `entries` and `entriesHigherLevel`
> Closes #2078

- subclass/Korvinagor; Circle of Pheromones.json
Added an aromatic enchanter druid subclass.
> Added Korvinagor; Circle of Pheromones

- subclass/Trevor Harnett; Forge Master Wizard.json
> Closes #2088

- subclass/Korvinagor; Arcane Ordnance Sorcerous Origin.json
Tweaked down overall power, clarified wording.
> Updated Arcane Ordnance Sorcerous Origin

- subclass/Korvinagor; Circle of Pheromones.json
Adjusted flavour text and capstone.
> Circle of Pheromones tweaks

- spell/LaserLlama; Laserllama's Spell Compendium.json
Added Hypnotic Pattern, Polymorph, Wall of Force, and Forcecage.
> Update LaserLlama; Laserllama's Spell Compendium.json

- class/LaserLlama; Alternate Bard.json
> Alternate Bard scaling hotfix

- subclass/Dusk Zargoth; Way of the Elements.json
A four elements themed subclass for monk with direct focus on combat.
> Create Dusk Zargoth; Way of the Elements.json

- class/Dusk Zargoth; Monk Rework.json
Master the Power of Ki and Martial Arts
> Add class "Monk Rework" via file upload

- class/KibblesTasty; Psion.json
- Fixed incorrect version info
- Updated class to latest version
- Fixed feature references and formatting
- Fixed reference names across the board
- Added some missing features
> Psion class update to latest version

- class/KibblesTasty; Psion.json
- Fixed broken subclass references
- Fixed botched `feature` formatting for feature filters
> Kibbles Psion latest version fixes

- subclass/Korvinagor; Circle of Dreams (Revised).json
> Updated Circle of Dreams (Revised)

- class/LaserLlama; Alternate Blood Hunter.json
- class/LaserLlama; Magus Class.json
replace `includes` with `dependencies`
> LL Quick Fix

- spell/somanyrobots, Omega Ankh; Spells That Don't Suck.json
Adjusted range error in Life Drain
> Update somanyrobots, Omega Ankh; Spells That Don't Suck.json

- spell/Korvinagor; Korvin's Spells and Spell Revisions.json
Added a counterpart to feather fall for druids and rangers.
> Added the Shrubdive spell

- class/AgenderArcee; The Martial Ranger.json
- class/Blubber Nibble; Noidrin's Record of Many Things.json
- class/Taron Pounds; Merchant.json
- class/Vincent Girgenti; The Nomad.json
- class/uI'mFromNASA; Yet Another Ranger Variant.json
- collection/Aeron Drake; Modern Handbook.json
- subclass/KibblesTasty; Oath of the Goodest Boi.json
> chore:sort props

- creature/Kobold Press; Tome of Beasts 3.json
> Update Kobold Press; Tome of Beasts 3.json

- class/LaserLlama; Alternate Blood Hunter.json
- class/LaserLlama; Savant.json
- class/LaserLlama; The Vessel.json
- creature/Aura; Aura's Homebrew.json
- subclass/LaserLlama; Primal Paths.json
Supports https://github.com/TheGiddyLimit/5etools-utils/pull/6
> fix subEntities and tokenUrls

- collection/hakr14; Weave of Karo.json
- item/hakr14; Weave of Karo - Items.json
moved to collection, marked previous file deprecated
> Weave of Karo 1.3b

- collection/Chronicle of Heroes; Voyager's Guide to Kyrmordia - Ley Lines & Nexuses.json
> Chronicle of Heroes - Ley Lines & Nexuses

- creature/William Rotor; Outclassed - The NPC Statblock Compendium.json
Don't put it under `*` you fool
> Fix fixing _copy

- collection/Nedrapter; Nedrapter's Expanded Dangers.json
Includes the most recently updated content.
> Update Nedrapter; Nedrapter's Expanded Dangers

- collection/EN Publishing; Level Up-Advanced 5th Edition Adventurer's Guide.json
BREW-501: Just the ~~tip~~ *maneuvers*
> A5E: BREW-501

- collection/Ross Hardy; Kunio's Guide to Seigai.json
Near complete apart from images.
> Adding Ross Hardy; Kunio's Guide to Seigai

- subclass/Korvinagor; Circle of the Butterfly.json
Added a chaotic, weather-manipulating druid subclass.
> Added Korvinagor; Circle of the Butterfly

- collection/Galdeveer; Tanks and Flanks.json
Added some new healing spells. Made some other small tweaks.
> New healing spells

- collection/Griffin Macaulay; The Griffon's Saddlebag, Book 3.json
**Updates:**
- Added book cover images
- Added custom fonts
> Update Griffon Saddlebag Book 3

- collection/Griffin Macaulay; The Griffon's Saddlebag, Book 1.json
> Update Griffon's Saddlebag Book 1

- class/Foxfire94; Blood Hunter Re-Balanced.json
- class/Foxfire94; Inquisitor.json
- class/Foxfire94; Lycanthrope.json
- class/TheFlameTouched; Ranger (Revised Spell-less).json
- creature/Foxfire94; Honourable Heroes.json
- creature/Foxfire94; Skaven.json
- item/Foxfire94; Armour, Items, and Weapons Galore.json
- race/Foxfire94; Sangheili.json
- spell/Foxfire94; Advanced Arcaneries 2.json
- subclass/Foxfire94; College of Metal Bard.json
- subclass/Foxfire94; Foxfire's Path of the Berserker Barbarian.json
- subclass/Foxfire94; Plague Domain.json
- subclass/Sam Becker; Battle Medic.json
Updates to 8 of my brews and 1 I contribute to along with 4 new brews added.
> Updates to 9 brews and 4 new added

- variantrule/Bovenbrew; Bovenbrew Weapon Arts.json
> Update Bovenbrew; Bovenbrew Weapon Arts.json

- race/PoinyHat; The Felis.json
Added the Felis Race from Pointy Hat
> Pointy Hat; The Felis

- book/MCDM Productions; Arcadia Issue 2.json
> Overhaul Arcadia 2

- collection/Griffin Macaulay; The Griffon's Saddlebag, Book 4.json
Updates:
- Added September 2024 items
- Added 2 Subclasses: 
- Oath of the Dreamwarden - Paladin
- Way of the Stormfist - Monk
> Update Griffon Saddlebag Book 4

- collection/AcidArmy; AcidArmy's Book of Crossovers.json
Closes #2276
Fixes: 
- Removed `targetSchema`, `$schema`
- Added `status`, `edition`
- Removed empty arrays
- Removed `additionalFromBackground` in `startingEquipment`, fixed tag bracket
> Add AcidArmy

- collection/badooga; The Hands of Vecna.json
Update Janara Nedath section, typo fixes
> Update badooga; The Hands of Vecna.json

- creature/MCDM Productions; Flee, Mortals!.json
Updates:
- Added missing creature images
- Added item images
> Flee Mortals Updates

- collection/Moiple Doiple; Monsters of Velimir.json.json
> Monsters of Velimir

- item/Wraith Wright Productions; Comprehensive Equipment Manual.json
> fix item text

- class/Foxfire94; Blood Hunter Re-Balanced.json
- class/Foxfire94; Inquisitor.json
- class/Foxfire94; Lycanthrope.json
- class/Foxfire94; Spellblade.json
- class/Foxfire94; Vampire.json
- creature/Foxfire94; Skaven.json
- race/Foxfire94; Basitin.json
- race/Foxfire94; Gnoll, Kitsune, Man-Ogre, Rat-men Races.json
- race/Foxfire94; Lupin.json
- race/Foxfire94; Sangheili.json
- spell/Foxfire94; Advanced Arcaneries 2.json
- subclass/Foxfire94; Blood Magic Sorcerous Origin.json
- subclass/Foxfire94; Brick Brawler Monk.json
- subclass/Foxfire94; Brute Fighter.json
- subclass/Foxfire94; College of Metal Bard.json
- subclass/Foxfire94; Oath Daemonicus Paladin.json
- subclass/Foxfire94; Primaris Lieutenant.json
- subclass/Foxfire94; Way of the Divine Blade Monk.json
- subclass/Foxfire94; Way of the Sohei Monk.json
- subclass/LeonardoDoujinshii; Water Domain Cleric.json
As per title, updates to some existing brews and 3 new additions.
> Updating brews and adding 3 new

- collection/Keith Baker; Dread Metrol - Into the Mists.json
Includes bestiary, adventure, Mastermaker subclass
image links to be fixed
> feat(DreadMetrol): add WIP version file

- background/DaveParkinglot; SelerimBackgroundEdits.json
> updated custom backgrounds

- subclass/Korvinagor; Swordcaller Sorcery.json
Added a sword-spamming Sorcerer subclass.
> Added Korvinagor; Swordcaller Sorcery

- collection/Griffin Macaulay; The Griffon's Saddlebag, Book 1.json
- collection/Griffin Macaulay; The Griffon's Saddlebag, Book 3.json
- collection/Griffin Macaulay; The Griffon's Saddlebag, Book 4.json
This fixes numerous GV items that broke with the '24 update.
> Update Griffon's Saddlebag Books 1, 3, & 4

- background/DaveParkinglot; SelerimBackgroundEdits.json
adding new student background + some fixes
> New Student Background

- collection/Lord Woolfy; Woolfy's Brew Cabinet.json
Added "Lord Woolfy; Woolfy's Brew Cabinet.json" to collection
> Added Lord Woolfy; Woolfy's Brew Cabinet.json

- collection/KibblesTasty; Kibbles' Compendium of Legends and Legacies.json
- Removed WIP status now that it's verified working
- Pulled PHB references to support '24 content
- Added conversion notes to book info
> Removed WIP

- deck/cool_gay_frog; Deck of Many More Things 2024.json
Resolves 5ET-1291
Closes #2357
> feat(5ET-1291): 2024 Deck of Many MORE Things

- class/MCDM Productions; The Talent and Psionics.json
> Update The Talent & Psionics

- adventure/Ghostfire Gaming; Dungeons of Drakkenheim In Search of the Smuggler’s Secrets.json
Adds grids for DoDkSearchSmugglersSecrets
> feat(DoDkSearchSmugglersSecrets): Grids

- class/The Baster; The Ruffian.json
> Add “The Ruffian” by The Baster

- background/alterNERDtive; 2024 Custom Background.json
See suggestion `PLUT-527` which is probably not very high priority. This can be used in the meantime.
> 2024 Custom Background by yours truly

- class/alterNERDtive; The Ruffian Revised.json
> Foundry integration fixes for “The Ruffian, Revised” by yours truly

- class/Laserllama; The Shifter.json
> Create `class/Laserllama; The Shifter.json`

- collection/Mage Hand Press; Valda's Spire of Secrets - Player Pack.json
> VSS: PP Update

- _img/Ar7/README.md
- book/MCDM Productions; Arcadia Issue 7.json
All Arcadia art in homebrew-img
> Migrate Art for Ar7

- creature/MCDM Productions; Flee, Mortals!.json
> Update MCDM Productions; Flee, Mortals!.json

- class/MCDM Productions; Beastheart.json
> Fix Typo in MCDM Productions; Beastheart.json

- adventure/Winghorn Press; Wild Sheep Chase.json
Running this for the 5th time and really just want a one-click import at this point.
Notably accompanied by scenes-repo PR
> Overhaul The Wild Sheep Chase

- race/oculyn; Songborne Species 1.9.json
made together with BlueOakMimic and santiarun
> oculyn's Songborne half siren species for 5e classic

- class/LaserLlama; Alternate Wizard.json
> Teaches Alt Wizard to play nice with the 2014 site

- class/KibblesTasty; Inventor.json
- Fix Inventor class being called "KibblesTasty's Inventor"
- Change the identifier and source name to fit with the other KT classes in the repo
- Fix spells not being added to the Artificer spell list
- Fix some spells incorrectly referencing the Artificer class in their description
> Update KibblesTasty; Inventor.json

- collection/Talon; Talon's Codex of Secrets.json
This first commit is mainly to get my foot in the door. It will soon include the whole document.
> Create Talon; Talon's Codex of Secrets.json

- class/SnowWolf; Blood Hunter (2024).json
https://homebrewery.naturalcrit.com/share/fcV-yiDorwjY
> Class: SnowWolf's Blood Hunter 2024

- class/LaserLlama; Alternate Warlock.json
Hopefully the json contains no more oopsies
> Mild fixes to Warlock

- class/LaserLlama; Alternate Fighter.json
- class/LaserLlama; Alternate Warlock.json
- optionalfeature/laserllama; Laserllama's Exploit Compendium.json
This will merge without problem, Peter, and may God have me shot in a carjacking this very night, if I'm wrong.
> Finally fixes the automatization for 3, 4 and 5th degree Exploits
